import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import type { Player } from '@/lib/database.types'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY

function getSupabase() {
  if (!supabaseUrl || !supabaseServiceKey) {
    return null
  }
  return createClient(supabaseUrl, supabaseServiceKey)
}

// Player categories for filtering
type PlayerCategory = 'all' | 'sb48' | '2025-hawks' | '2025-pats' | 'hof'

// Demo players data organized by category
const DEMO_PLAYERS: Player[] = [
  // ============================================
  // 2025 SEAHAWKS - Super Bowl LX Roster (24 players)
  // ============================================
  // OFFENSE
  {
    id: '2025-sea-sam-darnold',
    name: 'Sam Darnold',
    jersey_number: 14,
    position: 'Quarterback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3912547.png',
    image_validated: false,
    stats: { 'Pass Yds': '4,048', 'Pass TD': '25', 'Rating': '99.1' },
    bio: 'Seahawks QB - 2025 Season',
    super_bowl_highlight: 'Leading Seahawks to Super Bowl LX appearance',
    trivia: ['Led Seahawks to 14-3 record', 'Signed after breakout 2024 season in Minnesota'],
    display_order: 1,
    is_active: true,
  },
  {
    id: '2025-sea-kenneth-walker',
    name: 'Kenneth Walker III',
    jersey_number: 9,
    position: 'Running Back',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4567048.png',
    image_validated: false,
    stats: { 'Rush Yds': '1,027', 'Rush TD': '5', 'Yds/Carry': '4.6' },
    bio: 'Seahawks RB1 - 2025 Season',
    super_bowl_highlight: 'Key playoff performer',
    trivia: ['Rushed for over 1,000 yards in 2025', '2022 second-round pick from Michigan State'],
    display_order: 2,
    is_active: true,
  },
  {
    id: '2025-sea-george-holani',
    name: 'George Holani',
    jersey_number: 36,
    position: 'Running Back',
    image_url: null,
    image_validated: false,
    stats: { 'Rush Yds': '73', 'Rush TD': '1', 'Yds/Carry': '3.3' },
    bio: 'Seahawks RB2 - 2025 Season',
    super_bowl_highlight: 'Versatile backup running back',
    trivia: ['Boise State product', 'Strong pass blocker'],
    display_order: 3,
    is_active: true,
  },
  {
    id: '2025-sea-jaxon-smith-njigba',
    name: 'Jaxon Smith-Njigba',
    jersey_number: 11,
    position: 'Wide Receiver',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4430878.png',
    image_validated: false,
    stats: { 'Rec': '119', 'Rec Yds': '1,793', 'Rec TD': '10' },
    bio: 'Seahawks WR - 2025 NFL Receiving Leader',
    super_bowl_highlight: 'Led NFL in receiving yards heading into Super Bowl',
    trivia: ['Set Seahawks single-season receiving record', '2023 first-round pick from Ohio State'],
    display_order: 4,
    is_active: true,
  },
  {
    id: '2025-sea-cooper-kupp',
    name: 'Cooper Kupp',
    jersey_number: 10,
    position: 'Wide Receiver',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/2977187.png',
    image_validated: false,
    stats: { 'Rec': '47', 'Rec Yds': '593', 'Rec TD': '2' },
    bio: 'Seahawks WR - Super Bowl LVI MVP',
    super_bowl_highlight: 'Veteran leadership and clutch catches in playoffs',
    trivia: ['Super Bowl LVI MVP with Rams', 'Yakima, Washington native returns home'],
    display_order: 5,
    is_active: true,
  },
  {
    id: '2025-sea-rashid-shaheed',
    name: 'Rashid Shaheed',
    jersey_number: 22,
    position: 'Wide Receiver',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4032473.png',
    image_validated: false,
    stats: { 'Rec': '15', 'Rec Yds': '188', 'Rec TD': '0' },
    bio: 'Seahawks WR - Deep Threat',
    super_bowl_highlight: 'Elite deep threat with 4.36 speed',
    trivia: ['Acquired from Saints at trade deadline', 'Weber State product'],
    display_order: 6,
    is_active: true,
  },
  {
    id: '2025-sea-aj-barner',
    name: 'AJ Barner',
    jersey_number: 88,
    position: 'Tight End',
    image_url: null,
    image_validated: false,
    stats: { 'Rec': '52', 'Rec Yds': '519', 'Rec TD': '6' },
    bio: 'Seahawks TE - 2025 Season',
    super_bowl_highlight: 'Key red zone target in rookie season',
    trivia: ['Michigan product', '2024 fourth-round pick'],
    display_order: 7,
    is_active: true,
  },
  {
    id: '2025-sea-charles-cross',
    name: 'Charles Cross',
    jersey_number: 67,
    position: 'Offensive Tackle',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4426354.png',
    image_validated: false,
    stats: { 'Sacks Allowed': '3', 'Pressures': '18', 'Grade': '82.4' },
    bio: 'Seahawks LT - 2025 Season',
    super_bowl_highlight: 'Protecting Darnold\'s blind side',
    trivia: ['2022 first-round pick', 'Mississippi State standout'],
    display_order: 8,
    is_active: true,
  },
  {
    id: '2025-sea-josh-jones',
    name: 'Josh Jones',
    jersey_number: 74,
    position: 'Guard',
    image_url: null,
    image_validated: false,
    stats: { 'Sacks Allowed': '2', 'Pressures': '14', 'Grade': '76.8' },
    bio: 'Seahawks G - 2025 Season',
    super_bowl_highlight: 'Versatile G/T with 6 years experience',
    trivia: ['Houston product', 'Key free agent signing'],
    display_order: 9,
    is_active: true,
  },
  {
    id: '2025-sea-olu-oluwatimi',
    name: 'Olu Oluwatimi',
    jersey_number: 55,
    position: 'Center',
    image_url: null,
    image_validated: false,
    stats: { 'Snaps': '1,088', 'Sacks Allowed': '0', 'Grade': '75.8' },
    bio: 'Seahawks C - 2025 Season',
    super_bowl_highlight: 'Anchoring the offensive line',
    trivia: ['2023 Rimington Trophy winner at Michigan', 'Graduate transfer success story'],
    display_order: 10,
    is_active: true,
  },
  {
    id: '2025-sea-anthony-bradford',
    name: 'Anthony Bradford',
    jersey_number: 75,
    position: 'Guard',
    image_url: null,
    image_validated: false,
    stats: { 'Sacks Allowed': '2', 'Penalties': '4', 'Grade': '72.1' },
    bio: 'Seahawks RG - 2025 Season',
    super_bowl_highlight: 'Power run blocking specialist',
    trivia: ['LSU product', 'Known for nasty streak'],
    display_order: 11,
    is_active: true,
  },
  {
    id: '2025-sea-abraham-lucas',
    name: 'Abraham Lucas',
    jersey_number: 72,
    position: 'Offensive Tackle',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4361741.png',
    image_validated: false,
    stats: { 'Sacks Allowed': '4', 'Pressures': '22', 'Grade': '76.5' },
    bio: 'Seahawks RT - 2025 Season',
    super_bowl_highlight: 'Returned strong from 2024 knee injury',
    trivia: ['Washington State product', '2022 third-round pick'],
    display_order: 12,
    is_active: true,
  },
  // DEFENSE
  {
    id: '2025-sea-leonard-williams',
    name: 'Leonard Williams',
    jersey_number: 99,
    position: 'Defensive Tackle',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/2976212.png',
    image_validated: false,
    stats: { 'Sacks': '9.5', 'Tackles': '58', 'TFL': '12' },
    bio: 'Seahawks DT - 2025 Season',
    super_bowl_highlight: 'Dominant interior pass rusher',
    trivia: ['2-time Pro Bowl selection', 'USC product'],
    display_order: 13,
    is_active: true,
  },
  {
    id: '2025-sea-jarran-reed',
    name: 'Jarran Reed',
    jersey_number: 90,
    position: 'Nose Tackle',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3054850.png',
    image_validated: false,
    stats: { 'Sacks': '5.5', 'Tackles': '42', 'TFL': '8' },
    bio: 'Seahawks NT - 2025 Season',
    super_bowl_highlight: 'Run-stuffing anchor',
    trivia: ['Alabama national champion', 'Returned to Seattle in 2023'],
    display_order: 14,
    is_active: true,
  },
  {
    id: '2025-sea-byron-murphy',
    name: 'Byron Murphy II',
    jersey_number: 91,
    position: 'Defensive Tackle',
    image_url: null,
    image_validated: false,
    stats: { 'Sacks': '6.0', 'Tackles': '44', 'TFL': '9' },
    bio: 'Seahawks DT - 2025 Season',
    super_bowl_highlight: 'Interior pass rush specialist',
    trivia: ['Texas product', '2023 second-round pick'],
    display_order: 15,
    is_active: true,
  },
  {
    id: '2025-sea-boye-mafe',
    name: 'Boye Mafe',
    jersey_number: 53,
    position: 'Linebacker',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4361418.png',
    image_validated: false,
    stats: { 'Sacks': '11.5', 'Tackles': '48', 'FF': '3' },
    bio: 'Seahawks EDGE - 2025 Pro Bowl',
    super_bowl_highlight: 'Breakout pass rusher with double-digit sacks',
    trivia: ['Minnesota product', '2022 second-round pick'],
    display_order: 16,
    is_active: true,
  },
  {
    id: '2025-sea-ernest-jones',
    name: 'Ernest Jones IV',
    jersey_number: 13,
    position: 'Linebacker',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '126', 'Solo': '60', 'INT': '5', 'INT TD': '1' },
    bio: 'Seahawks LB - Defensive Captain',
    super_bowl_highlight: 'Leading tackler with 126 tackles and 5 INTs',
    trivia: ['South Carolina product', 'Acquired from Titans'],
    display_order: 17,
    is_active: true,
  },
  {
    id: '2025-sea-uchenna-nwosu',
    name: 'Uchenna Nwosu',
    jersey_number: 7,
    position: 'Linebacker',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '72', 'Sacks': '8.0', 'TFL': '10' },
    bio: 'Seahawks LB - 2025 Season',
    super_bowl_highlight: 'Edge rusher and run defender',
    trivia: ['USC product', 'Signed in 2022 free agency'],
    display_order: 18,
    is_active: true,
  },
  {
    id: '2025-sea-devon-witherspoon',
    name: 'Devon Witherspoon',
    jersey_number: 21,
    position: 'Cornerback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4429013.png',
    image_validated: false,
    stats: { 'Tackles': '72', 'Solo': '48', 'Pass Def': '16' },
    bio: 'Seahawks CB - 2025 All-Pro',
    super_bowl_highlight: 'Shutdown corner allowing lowest passer rating',
    trivia: ['2023 DROY finalist', 'Illinois product'],
    display_order: 19,
    is_active: true,
  },
  {
    id: '2025-sea-riq-woolen',
    name: 'Riq Woolen',
    jersey_number: 27,
    position: 'Cornerback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4379394.png',
    image_validated: false,
    stats: { 'Tackles': '52', 'INT': '3', 'Pass Def': '12' },
    bio: 'Seahawks CB - 2025 Season',
    super_bowl_highlight: 'Ball-hawking corner with elite length',
    trivia: ['6-foot-4 with 4.26 speed', 'UTSA product'],
    display_order: 20,
    is_active: true,
  },
  {
    id: '2025-sea-julian-love',
    name: 'Julian Love',
    jersey_number: 20,
    position: 'Safety',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3929856.png',
    image_validated: false,
    stats: { 'Tackles': '89', 'INT': '3', 'Pass Def': '8' },
    bio: 'Seahawks S - 2025 Season',
    super_bowl_highlight: 'Versatile safety making impact plays',
    trivia: ['Notre Dame product', 'Signed from Giants in 2023'],
    display_order: 21,
    is_active: true,
  },
  {
    id: '2025-sea-coby-bryant',
    name: 'Coby Bryant',
    jersey_number: 8,
    position: 'Safety',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '66', 'INT': '4', 'INT Yds': '43' },
    bio: 'Seahawks S - 2025 Season',
    super_bowl_highlight: 'Ball-hawking safety with 4 interceptions',
    trivia: ['Cincinnati product', '2022 Jim Thorpe Award winner'],
    display_order: 22,
    is_active: true,
  },
  // SPECIAL TEAMS
  {
    id: '2025-sea-jason-myers',
    name: 'Jason Myers',
    jersey_number: 5,
    position: 'Kicker',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/2515934.png',
    image_validated: false,
    stats: { 'FG%': '92.3%', 'FG Made': '24/26', 'Long': '56' },
    bio: 'Seahawks K - 2025 Season',
    super_bowl_highlight: 'Automatic from 50+ yards',
    trivia: ['Pro Bowl selection in 2018', 'Marist College product'],
    display_order: 23,
    is_active: true,
  },
  {
    id: '2025-sea-michael-dickson',
    name: 'Michael Dickson',
    jersey_number: 4,
    position: 'Punter',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3122899.png',
    image_validated: false,
    stats: { 'Avg': '48.2', 'Net': '44.1', 'Inside 20': '28' },
    bio: 'Seahawks P - 2025 Pro Bowl',
    super_bowl_highlight: 'Elite punter flipping field position',
    trivia: ['2018 Ray Guy Award winner', 'Australian-born'],
    display_order: 24,
    is_active: true,
  },
  // COACHING STAFF
  {
    id: '2025-sea-mike-macdonald',
    name: 'Mike Macdonald',
    jersey_number: 0,
    position: 'Head Coach',
    image_url: null,
    image_validated: false,
    stats: { 'Record': '14-3', 'NFC Seed': '1st', 'Division': 'NFC West' },
    bio: 'Seahawks Head Coach - 2nd Year',
    super_bowl_highlight: 'Youngest HC to lead team to Super Bowl since Sean McVay',
    trivia: ['9th head coach in franchise history', 'Former Ravens DC'],
    display_order: 25,
    is_active: true,
  },
  {
    id: '2025-sea-klint-kubiak',
    name: 'Klint Kubiak',
    jersey_number: 0,
    position: 'Offensive Coordinator',
    image_url: null,
    image_validated: false,
    stats: { 'Points/Game': '28.4', 'NFL Rank': '3rd', 'Pass Yds': '4,048' },
    bio: 'Seahawks OC - 2025 Season',
    super_bowl_highlight: 'Designed offense that maximized Darnold\'s abilities',
    trivia: ['Son of Super Bowl champion Gary Kubiak', 'Former Vikings OC'],
    display_order: 26,
    is_active: true,
  },
  {
    id: '2025-sea-aden-durde',
    name: 'Aden Durde',
    jersey_number: 0,
    position: 'Defensive Coordinator',
    image_url: null,
    image_validated: false,
    stats: { 'Points Allowed': '17.2', 'NFL Rank': '1st', 'Sacks': '48' },
    bio: 'Seahawks DC - 2025 Season',
    super_bowl_highlight: 'Led NFL\'s #1 scoring defense',
    trivia: ['British-born coach', 'Former Cowboys DC'],
    display_order: 27,
    is_active: true,
  },
  {
    id: '2025-sea-leslie-frazier',
    name: 'Leslie Frazier',
    jersey_number: 0,
    position: 'Assistant Head Coach',
    image_url: null,
    image_validated: false,
    stats: { 'HC Experience': '4 years', 'DC Experience': '10+ years', 'Super Bowls': '1 (player)' },
    bio: 'Seahawks Assistant HC - 2025 Season',
    super_bowl_highlight: 'Veteran leadership and defensive expertise',
    trivia: ['Former Vikings head coach', 'Won Super Bowl XX as player'],
    display_order: 28,
    is_active: true,
  },
  {
    id: '2025-sea-john-schneider',
    name: 'John Schneider',
    jersey_number: 0,
    position: 'General Manager',
    image_url: null,
    image_validated: false,
    stats: { 'Tenure': '16 years', 'Super Bowls': '1 (XLVIII)', 'Draft Picks': '100+' },
    bio: 'Seahawks GM - Architect of Dynasty',
    super_bowl_highlight: 'Built both Super Bowl XLVIII and LX rosters',
    trivia: ['Longest-tenured GM in NFL', 'Traded for Sam Darnold in 2025'],
    display_order: 29,
    is_active: true,
  },
  // ============================================
  // 2025 PATRIOTS - Super Bowl LX Opponent
  // ============================================
  // OFFENSE
  {
    id: '2025-pats-drake-maye',
    name: 'Drake Maye',
    jersey_number: 10,
    position: 'Quarterback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4432577.png',
    image_validated: false,
    stats: { 'Pass Yds': '4,394', 'Pass TD': '31', 'INT': '8', 'Rating': '113.5', 'CMP%': '72%' },
    bio: 'Patriots QB - 2025 Season',
    super_bowl_highlight: 'Led Patriots to Super Bowl in sophomore season',
    trivia: ['2024 first-round pick from North Carolina', 'Youngest QB in franchise history to start Super Bowl'],
    display_order: 101,
    is_active: true,
  },
  {
    id: '2025-pats-rhamondre-stevenson',
    name: 'Rhamondre Stevenson',
    jersey_number: 38,
    position: 'Running Back',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4259545.png',
    image_validated: false,
    stats: { 'Rush Yds': '603', 'Rush TD': '7', 'Rec': '32', 'Rec Yds': '345', 'Rec TD': '2' },
    bio: 'Patriots RB - 2025 Season',
    super_bowl_highlight: 'Veteran back powering Patriots offense',
    trivia: ['Oklahoma product', 'Elite pass-catching running back'],
    display_order: 102,
    is_active: true,
  },
  {
    id: '2025-pats-treveyon-henderson',
    name: 'TreVeyon Henderson',
    jersey_number: 28,
    position: 'Running Back',
    image_url: null,
    image_validated: false,
    stats: { 'Rush Yds': '911', 'Rush TD': '9', 'Rec': '35', 'Rec Yds': '221', 'Rec TD': '1' },
    bio: 'Patriots RB1 - 2025 Season',
    super_bowl_highlight: 'Explosive lead back with 911 rush yards',
    trivia: ['2025 second-round pick from Ohio State', 'Elite speed and burst'],
    display_order: 103,
    is_active: true,
  },
  {
    id: '2025-pats-stefon-diggs',
    name: 'Stefon Diggs',
    jersey_number: 8,
    position: 'Wide Receiver',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/16460.png',
    image_validated: false,
    stats: { 'Rec': '85', 'Rec Yds': '1,013', 'Rec TD': '4', 'Yds/Rec': '11.9' },
    bio: 'Patriots WR1 - 2025 Season',
    super_bowl_highlight: 'Veteran playmaker with 1,000+ yards',
    trivia: ['4-time Pro Bowl selection', 'Signed from Houston in 2025 free agency'],
    display_order: 104,
    is_active: true,
  },
  {
    id: '2025-pats-hunter-henry',
    name: 'Hunter Henry',
    jersey_number: 85,
    position: 'Tight End',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3051889.png',
    image_validated: false,
    stats: { 'Rec': '60', 'Rec Yds': '768', 'Rec TD': '7', 'Yds/Rec': '12.8' },
    bio: 'Patriots TE - 2025 Season',
    super_bowl_highlight: 'Red zone weapon with 7 TDs',
    trivia: ['Arkansas product', '2016 second-round pick'],
    display_order: 105,
    is_active: true,
  },
  {
    id: '2025-pats-mack-hollins',
    name: 'Mack Hollins',
    jersey_number: 13,
    position: 'Wide Receiver',
    image_url: null,
    image_validated: false,
    stats: { 'Rec': '46', 'Rec Yds': '550', 'Rec TD': '2', 'Yds/Rec': '12.0', 'Long': '54' },
    bio: 'Patriots WR - 2025 Season',
    super_bowl_highlight: 'Deep threat and special teams ace',
    trivia: ['North Carolina product', 'Veteran receiver'],
    display_order: 106,
    is_active: true,
  },
  {
    id: '2025-pats-kayshon-boutte',
    name: 'Kayshon Boutte',
    jersey_number: 0,
    position: 'Wide Receiver',
    image_url: null,
    image_validated: false,
    stats: { 'Rec': '33', 'Rec Yds': '551', 'Rec TD': '6', 'Yds/Rec': '16.7', 'Long': '39' },
    bio: 'Patriots WR - 2025 Season',
    super_bowl_highlight: 'Deep threat with 6 TDs',
    trivia: ['LSU product', '2023 sixth-round pick'],
    display_order: 107,
    is_active: true,
  },
  {
    id: '2025-pats-austin-hooper',
    name: 'Austin Hooper',
    jersey_number: 81,
    position: 'Tight End',
    image_url: null,
    image_validated: false,
    stats: { 'Rec': '32', 'Rec Yds': '348', 'Rec TD': '3' },
    bio: 'Patriots TE2 - 2025 Season',
    super_bowl_highlight: 'Veteran blocking tight end',
    trivia: ['Stanford product', 'Two-time Pro Bowl selection'],
    display_order: 108,
    is_active: true,
  },
  {
    id: '2025-pats-will-campbell',
    name: 'Will Campbell',
    jersey_number: 70,
    position: 'Offensive Tackle',
    image_url: null,
    image_validated: false,
    stats: { 'Sacks Allowed': '3', 'Pressures': '18', 'Grade': '78.4' },
    bio: 'Patriots T - 2025 Season',
    super_bowl_highlight: 'Protecting Maye\'s blind side',
    trivia: ['LSU product', '2025 first-round pick'],
    display_order: 109,
    is_active: true,
  },
  {
    id: '2025-pats-caedan-wallace',
    name: 'Caedan Wallace',
    jersey_number: 76,
    position: 'Offensive Tackle',
    image_url: null,
    image_validated: false,
    stats: { 'Sacks Allowed': '4', 'Pressures': '24', 'Grade': '74.8' },
    bio: 'Patriots T - 2025 Season',
    super_bowl_highlight: 'Versatile tackle',
    trivia: ['Penn State product', '2024 third-round pick'],
    display_order: 110,
    is_active: true,
  },
  {
    id: '2025-pats-mike-onwenu',
    name: 'Mike Onwenu',
    jersey_number: 71,
    position: 'Offensive Lineman',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3915483.png',
    image_validated: false,
    stats: { 'Sacks Allowed': '2', 'Penalties': '2', 'Grade': '81.4' },
    bio: 'Patriots OL - 2025 Season',
    super_bowl_highlight: 'Elite pass protector',
    trivia: ['Michigan product', 'Pro Bowl caliber'],
    display_order: 111,
    is_active: true,
  },
  {
    id: '2025-pats-vederian-lowe',
    name: 'Vederian Lowe',
    jersey_number: 73,
    position: 'Offensive Tackle',
    image_url: null,
    image_validated: false,
    stats: { 'Sacks Allowed': '5', 'Pressures': '28', 'Grade': '71.2' },
    bio: 'Patriots T - 2025 Season',
    super_bowl_highlight: 'Physical run blocker',
    trivia: ['Illinois product', 'Started all 17 games'],
    display_order: 112,
    is_active: true,
  },
  // DEFENSE
  {
    id: '2025-pats-christian-barmore',
    name: 'Christian Barmore',
    jersey_number: 90,
    position: 'Defensive Tackle',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4360238.png',
    image_validated: false,
    stats: { 'Sacks': '6.0', 'Tackles': '38', 'TFL': '11' },
    bio: 'Patriots DT - 2025 Season',
    super_bowl_highlight: 'Interior pass rush dominance',
    trivia: ['Alabama product', '2021 second-round pick'],
    display_order: 113,
    is_active: true,
  },
  {
    id: '2025-pats-milton-williams',
    name: 'Milton Williams',
    jersey_number: 93,
    position: 'Defensive Tackle',
    image_url: null,
    image_validated: false,
    stats: { 'Sacks': '4.5', 'Tackles': '42', 'TFL': '8' },
    bio: 'Patriots DT - 2025 Season',
    super_bowl_highlight: 'Versatile interior defender',
    trivia: ['Louisiana Tech product', 'Acquired from Eagles'],
    display_order: 114,
    is_active: true,
  },
  {
    id: '2025-pats-harold-landry',
    name: 'Harold Landry III',
    jersey_number: 58,
    position: 'Outside Linebacker',
    image_url: null,
    image_validated: false,
    stats: { 'Sacks': '11.0', 'Tackles': '56', 'FF': '4' },
    bio: 'Patriots EDGE - 2025 Season',
    super_bowl_highlight: 'Elite pass rusher anchoring defense',
    trivia: ['Boston College product', 'Signed from Titans'],
    display_order: 115,
    is_active: true,
  },
  {
    id: '2025-pats-robert-spillane',
    name: 'Robert Spillane',
    jersey_number: 41,
    position: 'Linebacker',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '97', 'Sacks': '1.0', 'INT': '2' },
    bio: 'Patriots LB - 2025 Season',
    super_bowl_highlight: 'Leading tackler with 97 tackles',
    trivia: ['Western Michigan product', 'Signed from Raiders'],
    display_order: 116,
    is_active: true,
  },
  {
    id: '2025-pats-jahlani-tavai',
    name: 'Jahlani Tavai',
    jersey_number: 48,
    position: 'Linebacker',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '78', 'Sacks': '1.5', 'TFL': '6' },
    bio: 'Patriots LB - 2025 Season',
    super_bowl_highlight: 'Versatile linebacker',
    trivia: ['Hawaii product', 'Key special teams contributor'],
    display_order: 117,
    is_active: true,
  },
  {
    id: '2025-pats-marte-mapu',
    name: 'Marte Mapu',
    jersey_number: 32,
    position: 'Linebacker',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '65', 'INT': '1', 'Pass Def': '5' },
    bio: 'Patriots LB - 2025 Season',
    super_bowl_highlight: 'Hybrid safety/linebacker with key interception',
    trivia: ['Sacramento State product', '2023 third-round pick'],
    display_order: 118,
    is_active: true,
  },
  {
    id: '2025-pats-christian-gonzalez',
    name: 'Christian Gonzalez',
    jersey_number: 0,
    position: 'Cornerback',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '69', 'INT': '0', 'Pass Def': '14' },
    bio: 'Patriots CB - 2025 All-Pro',
    super_bowl_highlight: 'Elite shutdown corner - opponents avoid his side',
    trivia: ['Oregon product', '2023 first-round pick'],
    display_order: 119,
    is_active: true,
  },
  {
    id: '2025-pats-carlton-davis',
    name: 'Carlton Davis III',
    jersey_number: 24,
    position: 'Cornerback',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '54', 'INT': '4', 'Pass Def': '12' },
    bio: 'Patriots CB - 2025 Season',
    super_bowl_highlight: 'Physical press corner',
    trivia: ['Auburn product', 'Super Bowl LV champion'],
    display_order: 120,
    is_active: true,
  },
  {
    id: '2025-pats-marcus-jones',
    name: 'Marcus Jones',
    jersey_number: 25,
    position: 'Cornerback',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '42', 'INT': '3', 'INT TD': '1', 'Pass Def': '8' },
    bio: 'Patriots CB - 2025 Season',
    super_bowl_highlight: 'Ball hawk with 3 INTs and a pick-six',
    trivia: ['Houston product', '2022 third-round pick'],
    display_order: 121,
    is_active: true,
  },
  {
    id: '2025-pats-craig-woodson',
    name: 'Craig Woodson',
    jersey_number: 21,
    position: 'Safety',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '79', 'INT': '0', 'Pass Def': '6' },
    bio: 'Patriots S - 2025 Season',
    super_bowl_highlight: 'Sure tackler with 79 stops',
    trivia: ['Texas product', '2025 draft pick'],
    display_order: 122,
    is_active: true,
  },
  {
    id: '2025-pats-jaylinn-hawkins',
    name: 'Jaylinn Hawkins',
    jersey_number: 33,
    position: 'Safety',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '71', 'INT': '4', 'Pass Def': '7' },
    bio: 'Patriots S - 2025 Season',
    super_bowl_highlight: 'Team INT leader with 4 picks',
    trivia: ['California product', 'Former Falcons safety'],
    display_order: 129,
    is_active: true,
  },
  {
    id: '2025-pats-christian-elliss',
    name: 'Christian Elliss',
    jersey_number: 52,
    position: 'Linebacker',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '94', 'TFL': '7', 'Sacks': '1.5' },
    bio: 'Patriots LB - 2025 Season',
    super_bowl_highlight: 'High-motor linebacker with 94 tackles',
    trivia: ['Idaho product', 'Former Vikings LB'],
    display_order: 130,
    is_active: true,
  },
  {
    id: '2025-pats-jack-gibbens',
    name: 'Jack Gibbens',
    jersey_number: 44,
    position: 'Linebacker',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '81', 'TFL': '5', 'Sacks': '1.0' },
    bio: 'Patriots LB - 2025 Season',
    super_bowl_highlight: 'Reliable tackler with 81 stops',
    trivia: ['Minnesota product', 'Key special teams contributor'],
    display_order: 131,
    is_active: true,
  },
  // ADDITIONAL OFFENSE
  {
    id: '2025-pats-tommy-devito',
    name: 'Tommy DeVito',
    jersey_number: 3,
    position: 'Quarterback',
    image_url: null,
    image_validated: false,
    stats: { 'Pass Yds': '0', 'Pass TD': '0', 'INT': '0' },
    bio: 'Patriots QB3 - 2025 Season',
    super_bowl_highlight: 'Experienced backup quarterback',
    trivia: ['Illinois product', 'Former Giants starter'],
    display_order: 141,
    is_active: true,
  },
  {
    id: '2025-pats-joshua-dobbs',
    name: 'Joshua Dobbs',
    jersey_number: 5,
    position: 'Quarterback',
    image_url: null,
    image_validated: false,
    stats: { 'Pass Yds': '0', 'Pass TD': '0', 'INT': '0' },
    bio: 'Patriots QB2 - 2025 Season',
    super_bowl_highlight: 'Veteran backup with starting experience',
    trivia: ['Tennessee product', 'Aerospace engineer'],
    display_order: 142,
    is_active: true,
  },
  {
    id: '2025-pats-demario-douglas',
    name: 'DeMario Douglas',
    jersey_number: 3,
    position: 'Wide Receiver',
    image_url: null,
    image_validated: false,
    stats: { 'Rec': '68', 'Rec Yds': '824', 'Rec TD': '5' },
    bio: 'Patriots WR - 2025 Season',
    super_bowl_highlight: 'Quick slot receiver',
    trivia: ['Liberty product', 'Undrafted gem'],
    display_order: 143,
    is_active: true,
  },
  {
    id: '2025-pats-efton-chism',
    name: 'Efton Chism III',
    jersey_number: 88,
    position: 'Wide Receiver',
    image_url: null,
    image_validated: false,
    stats: { 'Rec': '12', 'Rec Yds': '145', 'Rec TD': '1' },
    bio: 'Patriots WR - 2025 Season',
    super_bowl_highlight: 'Rookie receiver with upside',
    trivia: ['Arkansas product', '2025 draft pick'],
    display_order: 144,
    is_active: true,
  },
  {
    id: '2025-pats-kyle-williams',
    name: 'Kyle Williams',
    jersey_number: 18,
    position: 'Wide Receiver',
    image_url: null,
    image_validated: false,
    stats: { 'Rec': '8', 'Rec Yds': '95', 'Rec TD': '0' },
    bio: 'Patriots WR - 2025 Season',
    super_bowl_highlight: 'Depth receiver',
    trivia: ['Arizona State product', 'Key special teams player'],
    display_order: 145,
    is_active: true,
  },
  {
    id: '2025-pats-jack-westover',
    name: 'Jack Westover',
    jersey_number: 47,
    position: 'Fullback',
    image_url: null,
    image_validated: false,
    stats: { 'Rec': '5', 'Rec Yds': '42', 'Rush TD': '1' },
    bio: 'Patriots FB - 2025 Season',
    super_bowl_highlight: 'Lead blocker in short yardage',
    trivia: ['BYU product', 'Key special teams contributor'],
    display_order: 146,
    is_active: true,
  },
  {
    id: '2025-pats-cj-dippre',
    name: 'CJ Dippre',
    jersey_number: 86,
    position: 'Tight End',
    image_url: null,
    image_validated: false,
    stats: { 'Rec': '15', 'Rec Yds': '168', 'Rec TD': '2' },
    bio: 'Patriots TE - 2025 Season',
    super_bowl_highlight: 'Blocking tight end with receiving upside',
    trivia: ['Alabama product', '2025 draft pick'],
    display_order: 147,
    is_active: true,
  },
  {
    id: '2025-pats-morgan-moses',
    name: 'Morgan Moses',
    jersey_number: 78,
    position: 'Offensive Tackle',
    image_url: null,
    image_validated: false,
    stats: { 'Sacks Allowed': '4', 'Pressures': '22', 'Grade': '74.5' },
    bio: 'Patriots T - 2025 Season',
    super_bowl_highlight: 'Veteran tackle depth',
    trivia: ['Virginia product', '10+ year NFL veteran'],
    display_order: 148,
    is_active: true,
  },
  {
    id: '2025-pats-jared-wilson',
    name: 'Jared Wilson',
    jersey_number: 62,
    position: 'Center',
    image_url: null,
    image_validated: false,
    stats: { 'Sacks Allowed': '1', 'Pressures': '8', 'Grade': '72.1' },
    bio: 'Patriots C - 2025 Season',
    super_bowl_highlight: 'Reliable interior lineman',
    trivia: ['Georgia product', 'Key depth piece'],
    display_order: 149,
    is_active: true,
  },
  {
    id: '2025-pats-ben-brown',
    name: 'Ben Brown',
    jersey_number: 60,
    position: 'Center',
    image_url: null,
    image_validated: false,
    stats: { 'Sacks Allowed': '0', 'Pressures': '5', 'Grade': '68.4' },
    bio: 'Patriots C - 2025 Season',
    super_bowl_highlight: 'Interior line depth',
    trivia: ['Ole Miss product', 'Versatile backup'],
    display_order: 150,
    is_active: true,
  },
  {
    id: '2025-pats-garrett-bradbury',
    name: 'Garrett Bradbury',
    jersey_number: 56,
    position: 'Center',
    image_url: null,
    image_validated: false,
    stats: { 'Sacks Allowed': '2', 'Pressures': '12', 'Grade': '71.8' },
    bio: 'Patriots C - 2025 Season',
    super_bowl_highlight: 'Veteran center depth',
    trivia: ['NC State product', 'Former Vikings starter'],
    display_order: 151,
    is_active: true,
  },
  {
    id: '2025-pats-thayer-munford',
    name: 'Thayer Munford Jr.',
    jersey_number: 77,
    position: 'Offensive Tackle',
    image_url: null,
    image_validated: false,
    stats: { 'Sacks Allowed': '3', 'Pressures': '18', 'Grade': '70.2' },
    bio: 'Patriots T - 2025 Season',
    super_bowl_highlight: 'Swing tackle',
    trivia: ['Ohio State product', 'Versatile lineman'],
    display_order: 152,
    is_active: true,
  },
  {
    id: '2025-pats-marcus-bryant',
    name: 'Marcus Bryant',
    jersey_number: 65,
    position: 'Offensive Tackle',
    image_url: null,
    image_validated: false,
    stats: { 'Sacks Allowed': '2', 'Pressures': '14', 'Grade': '68.5' },
    bio: 'Patriots T - 2025 Season',
    super_bowl_highlight: 'Developmental tackle',
    trivia: ['Wisconsin product', 'Practice squad call-up'],
    display_order: 153,
    is_active: true,
  },
  // ADDITIONAL DEFENSE
  {
    id: '2025-pats-klavon-chaisson',
    name: "K'Lavon Chaisson",
    jersey_number: 53,
    position: 'Linebacker',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '32', 'Sacks': '4.5', 'TFL': '6' },
    bio: 'Patriots LB - 2025 Season',
    super_bowl_highlight: 'Edge rusher off the bench',
    trivia: ['LSU product', 'Former first-round pick'],
    display_order: 154,
    is_active: true,
  },
  {
    id: '2025-pats-khyiris-tonga',
    name: 'Khyiris Tonga',
    jersey_number: 95,
    position: 'Defensive Lineman',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '28', 'Sacks': '2.0', 'TFL': '4' },
    bio: 'Patriots DL - 2025 Season',
    super_bowl_highlight: 'Run-stuffing nose tackle',
    trivia: ['BYU product', 'Interior depth'],
    display_order: 155,
    is_active: true,
  },
  {
    id: '2025-pats-cory-durden',
    name: 'Cory Durden',
    jersey_number: 97,
    position: 'Defensive Tackle',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '22', 'Sacks': '1.5', 'TFL': '3' },
    bio: 'Patriots DT - 2025 Season',
    super_bowl_highlight: 'Interior rotation player',
    trivia: ['NC State product', 'Key depth piece'],
    display_order: 156,
    is_active: true,
  },
  {
    id: '2025-pats-bradyn-swinson',
    name: 'Bradyn Swinson',
    jersey_number: 50,
    position: 'Linebacker',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '18', 'Sacks': '2.0', 'TFL': '3' },
    bio: 'Patriots LB - 2025 Season',
    super_bowl_highlight: 'Rookie edge defender',
    trivia: ['LSU product', '2025 draft pick'],
    display_order: 157,
    is_active: true,
  },
  {
    id: '2025-pats-elijah-ponder',
    name: 'Elijah Ponder',
    jersey_number: 54,
    position: 'Linebacker',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '15', 'Sacks': '0.5', 'TFL': '2' },
    bio: 'Patriots LB - 2025 Season',
    super_bowl_highlight: 'Special teams contributor',
    trivia: ['Florida State product', 'Undrafted free agent'],
    display_order: 158,
    is_active: true,
  },
  {
    id: '2025-pats-chad-muma',
    name: 'Chad Muma',
    jersey_number: 45,
    position: 'Linebacker',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '35', 'INT': '1', 'TFL': '4' },
    bio: 'Patriots LB - 2025 Season',
    super_bowl_highlight: 'Off-ball linebacker depth',
    trivia: ['Wyoming product', 'Former Jaguars starter'],
    display_order: 159,
    is_active: true,
  },
  {
    id: '2025-pats-anfernee-jennings',
    name: 'Anfernee Jennings',
    jersey_number: 59,
    position: 'Linebacker',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '28', 'Sacks': '1.0', 'TFL': '3' },
    bio: 'Patriots LB - 2025 Season',
    super_bowl_highlight: 'Veteran edge depth',
    trivia: ['Alabama product', '2020 third-round pick'],
    display_order: 160,
    is_active: true,
  },
  {
    id: '2025-pats-alex-austin',
    name: 'Alex Austin',
    jersey_number: 27,
    position: 'Cornerback',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '25', 'INT': '1', 'Pass Def': '5' },
    bio: 'Patriots CB - 2025 Season',
    super_bowl_highlight: 'Depth cornerback',
    trivia: ['Oregon State product', 'Special teams ace'],
    display_order: 161,
    is_active: true,
  },
  {
    id: '2025-pats-charles-woods',
    name: 'Charles Woods',
    jersey_number: 36,
    position: 'Cornerback',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '18', 'INT': '0', 'Pass Def': '3' },
    bio: 'Patriots CB - 2025 Season',
    super_bowl_highlight: 'Nickel corner depth',
    trivia: ['Notre Dame product', 'Key special teams player'],
    display_order: 162,
    is_active: true,
  },
  {
    id: '2025-pats-brenden-schooler',
    name: 'Brenden Schooler',
    jersey_number: 40,
    position: 'Safety',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '22', 'INT': '0', 'Pass Def': '2' },
    bio: 'Patriots S - 2025 Season',
    super_bowl_highlight: 'Special teams captain',
    trivia: ['Texas product', 'Core special teamer'],
    display_order: 163,
    is_active: true,
  },
  {
    id: '2025-pats-kobee-minor',
    name: 'Kobee Minor',
    jersey_number: 39,
    position: 'Defensive Back',
    image_url: null,
    image_validated: false,
    stats: { 'Tackles': '12', 'INT': '0', 'Pass Def': '2' },
    bio: 'Patriots DB - 2025 Season',
    super_bowl_highlight: 'Versatile defensive back',
    trivia: ['Georgia product', 'Rookie contributor'],
    display_order: 164,
    is_active: true,
  },
  // SPECIAL TEAMS
  {
    id: '2025-pats-andres-borregales',
    name: 'Andres Borregales',
    jersey_number: 6,
    position: 'Placekicker',
    image_url: null,
    image_validated: false,
    stats: { 'FG%': '86.5%', 'FG Made': '26/30', 'Long': '54' },
    bio: 'Patriots K - 2025 Season',
    super_bowl_highlight: 'Clutch kicker',
    trivia: ['Miami product', 'Undrafted free agent'],
    display_order: 123,
    is_active: true,
  },
  {
    id: '2025-pats-bryce-baringer',
    name: 'Bryce Baringer',
    jersey_number: 17,
    position: 'Punter',
    image_url: null,
    image_validated: false,
    stats: { 'Avg': '47.8', 'Net': '43.2', 'Inside 20': '24' },
    bio: 'Patriots P - 2025 Season',
    super_bowl_highlight: 'Elite hang time and directional punting',
    trivia: ['Michigan State product', '2023 sixth-round pick'],
    display_order: 124,
    is_active: true,
  },
  // COACHING STAFF
  {
    id: '2025-pats-mike-vrabel',
    name: 'Mike Vrabel',
    jersey_number: 0,
    position: 'Head Coach',
    image_url: null,
    image_validated: false,
    stats: { 'Record': '14-3', 'AFC Seed': '1st', 'Division': 'AFC East' },
    bio: 'Patriots Head Coach - 1st Year',
    super_bowl_highlight: 'Return to New England where he won 3 Super Bowls as player',
    trivia: ['Won 3 Super Bowls as Patriots LB', 'Former Titans head coach'],
    display_order: 125,
    is_active: true,
  },
  {
    id: '2025-pats-josh-mcdaniels',
    name: 'Josh McDaniels',
    jersey_number: 0,
    position: 'Offensive Coordinator',
    image_url: null,
    image_validated: false,
    stats: { 'Points/Game': '28.8', 'NFL Rank': '2nd', 'Pass Yds': '3,892' },
    bio: 'Patriots OC - 2025 Season',
    super_bowl_highlight: 'Reunited with Patriots to develop Drake Maye',
    trivia: ['6-time Super Bowl champion as coordinator', 'Returned to New England in 2025'],
    display_order: 126,
    is_active: true,
  },
  {
    id: '2025-pats-demarcus-covington',
    name: 'DeMarcus Covington',
    jersey_number: 0,
    position: 'Defensive Coordinator',
    image_url: null,
    image_validated: false,
    stats: { 'Points Allowed': '18.8', 'NFL Rank': '4th', 'Takeaways': '28' },
    bio: 'Patriots DC - 2025 Season',
    super_bowl_highlight: 'Aggressive defense creating turnovers',
    trivia: ['Former Patriots DL coach', 'Implementing aggressive scheme'],
    display_order: 127,
    is_active: true,
  },
  {
    id: '2025-pats-eliot-wolf',
    name: 'Eliot Wolf',
    jersey_number: 0,
    position: 'General Manager',
    image_url: null,
    image_validated: false,
    stats: { 'FA Signings': '$360M', 'Draft': 'Campbell, Henderson', 'Record': '14-3' },
    bio: 'Patriots GM - 2025 Season',
    super_bowl_highlight: 'Assembled roster through aggressive free agency',
    trivia: ['Son of former Packers GM Ron Wolf', 'Key signings: Diggs, Landry, Davis'],
    display_order: 128,
    is_active: true,
  },
  // ============================================
  // SUPER BOWL XLVIII HEROES (6 players)
  // ============================================
  {
    id: 'sbxlviii-russell-wilson',
    name: 'Russell Wilson',
    jersey_number: 3,
    position: 'Quarterback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/14881.png',
    image_validated: false,
    stats: { 'Pass Yds': '206', 'Pass TD': '2', 'Rating': '123.1' },
    bio: 'Super Bowl XLVIII Champion QB',
    super_bowl_highlight: 'Led the Seahawks to a 43-8 victory in Super Bowl XLVIII',
    trivia: ['Became 2nd Black QB to win a Super Bowl', 'Led game-opening 80-yard TD drive'],
    display_order: 201,
    is_active: false,
  },
  {
    id: 'sbxlviii-marshawn-lynch',
    name: 'Marshawn Lynch',
    jersey_number: 24,
    position: 'Running Back',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/10456.png',
    image_validated: false,
    stats: { 'Rush Yds': '39', 'Rush TD': '1', 'Carries': '15' },
    bio: 'Super Bowl XLVIII Champion RB - Beast Mode',
    super_bowl_highlight: 'Beast Mode touchdown run in Super Bowl XLVIII',
    trivia: ['Scored Seahawks first Super Bowl TD', 'Famous Beast Quake run in 2011 playoffs'],
    display_order: 202,
    is_active: false,
  },
  {
    id: 'sbxlviii-richard-sherman',
    name: 'Richard Sherman',
    jersey_number: 25,
    position: 'Cornerback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/14086.png',
    image_validated: false,
    stats: { 'Tackles': '3', 'Pass Def': '2', 'Pro Bowls': '5' },
    bio: 'Legion of Boom - All-Pro Corner',
    super_bowl_highlight: 'Key interception sealing NFC Championship',
    trivia: ['3-time First-Team All-Pro', 'Stanford graduate'],
    display_order: 203,
    is_active: false,
  },
  {
    id: 'sbxlviii-malcolm-smith',
    name: 'Malcolm Smith',
    jersey_number: 53,
    position: 'Linebacker',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/15116.png',
    image_validated: false,
    stats: { 'Tackles': '10', 'INT': '1', 'INT TD': '1' },
    bio: 'Super Bowl XLVIII MVP',
    super_bowl_highlight: 'Super Bowl XLVIII MVP with pick-six',
    trivia: ['Returned interception 69 yards for TD', 'Also recovered a fumble'],
    display_order: 204,
    is_active: false,
  },
  {
    id: 'sbxlviii-earl-thomas',
    name: 'Earl Thomas',
    jersey_number: 29,
    position: 'Safety',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/13251.png',
    image_validated: false,
    stats: { 'Tackles': '5', 'Pass Def': '2', 'Pro Bowls': '7' },
    bio: 'Legion of Boom - Elite Free Safety',
    super_bowl_highlight: 'Legion of Boom leader, 2 interceptions in playoffs',
    trivia: ['3-time First-Team All-Pro', 'Fastest safety in LOB'],
    display_order: 205,
    is_active: false,
  },
  {
    id: 'sbxlviii-kam-chancellor',
    name: 'Kam Chancellor',
    jersey_number: 31,
    position: 'Safety',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/13722.png',
    image_validated: false,
    stats: { 'Tackles': '7', 'FF': '1', 'Pass Def': '1' },
    bio: 'Legion of Boom - The Enforcer',
    super_bowl_highlight: 'Devastating hits and forced fumbles',
    trivia: ['Known as Bam Bam Kam', '4-time Pro Bowl selection'],
    display_order: 206,
    is_active: false,
  },
  // ============================================
  // HALL OF FAME LEGENDS (3 players)
  // ============================================
  {
    id: 'hof-steve-largent',
    name: 'Steve Largent',
    jersey_number: 80,
    position: 'Wide Receiver',
    image_url: 'https://www.profootballhof.com/pfhof/media/Default/Items/Largent_Steve_HS_150.jpg',
    image_validated: false,
    stats: { 'HOF Class': '1995', 'Career Rec': '819', 'Career TD': '100' },
    bio: 'Seahawks Legend - Hall of Fame (1995)',
    super_bowl_highlight: 'Franchise icon before Super Bowl era',
    trivia: ['First Seahawk in Hall of Fame', 'Played 14 years with Seattle'],
    display_order: 301,
    is_active: false,
  },
  {
    id: 'hof-walter-jones',
    name: 'Walter Jones',
    jersey_number: 71,
    position: 'Offensive Tackle',
    image_url: 'https://www.profootballhof.com/pfhof/media/Default/Items/Jones_Walter_HS-Capsule.jpg',
    image_validated: false,
    stats: { 'HOF Class': '2014', 'Pro Bowls': '9', 'All-Pro': '4x' },
    bio: 'Seahawks Legend - Hall of Fame (2014)',
    super_bowl_highlight: 'Protected QBs for 13 seasons',
    trivia: ['One of greatest LTs ever', 'Only 23 sacks allowed in career'],
    display_order: 302,
    is_active: false,
  },
  {
    id: 'hof-cortez-kennedy',
    name: 'Cortez Kennedy',
    jersey_number: 96,
    position: 'Defensive Tackle',
    image_url: 'https://www.profootballhof.com/pfhof/media/Default/Items/Kennedy_Cortez_Action_Bio.jpg',
    image_validated: false,
    stats: { 'HOF Class': '2012', 'Pro Bowls': '8', 'Sacks': '58' },
    bio: 'Seahawks Legend - Hall of Fame (2012)',
    super_bowl_highlight: 'Franchise defensive star',
    trivia: ['1992 NFL Defensive Player of the Year', '8-time Pro Bowl selection'],
    display_order: 303,
    is_active: false,
  },
]

// Filter players by category using display_order ranges and is_active flag
// Database structure:
// - 2025 Seahawks: is_active = true, display_order 1-30
// - 2025 Patriots: is_active = true, display_order 100-170
// - Super Bowl XLVIII Heroes: is_active = false, display_order 200-220
// - Hall of Fame: is_active = false, display_order 300-320
function filterByCategory(players: Player[], category: PlayerCategory): Player[] {
  switch (category) {
    case 'sb48':
      return players.filter(p => !p.is_active && p.display_order >= 200 && p.display_order < 250)
    case '2025-hawks':
      return players.filter(p => p.is_active === true && p.display_order >= 1 && p.display_order < 50)
    case '2025-pats':
      return players.filter(p => p.is_active === true && p.display_order >= 100 && p.display_order < 200)
    case 'hof':
      return players.filter(p => !p.is_active && p.display_order >= 300 && p.display_order < 350)
    case 'all':
    default:
      return players
  }
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const position = searchParams.get('position')
    const category = (searchParams.get('category') || 'sb48') as PlayerCategory

    const supabase = getSupabase()

    // Demo mode
    if (!supabase) {
      let players = filterByCategory([...DEMO_PLAYERS], category)

      if (position && position !== 'all') {
        players = players.filter(p =>
          p.position.toLowerCase().includes(position.toLowerCase())
        )
      }

      // Sort by display_order
      players.sort((a, b) => a.display_order - b.display_order)

      return NextResponse.json({
        players,
        total: players.length,
        category,
      })
    }

    // Build query - get all players (we'll filter by category)
    let query = supabase
      .from('players')
      .select('*')
      .order('display_order', { ascending: true })

    if (position && position !== 'all') {
      query = query.ilike('position', `%${position}%`)
    }

    const { data: allPlayers, error } = await query

    if (error) {
      console.error('Players fetch error:', error)
      return NextResponse.json(
        { error: 'Failed to fetch players' },
        { status: 500 }
      )
    }

    // Filter by category
    const players = filterByCategory(allPlayers || [], category)

    return NextResponse.json({
      players,
      total: players.length,
      category,
    })

  } catch (error) {
    console.error('Players error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
