import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import type { Player } from '@/lib/database.types'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY

function getSupabase() {
  if (!supabaseUrl || !supabaseServiceKey) {
    return null
  }
  return createClient(supabaseUrl, supabaseServiceKey)
}

// Player categories for filtering
type PlayerCategory = 'all' | 'sb48' | '2025-hawks' | '2025-pats' | 'hof'

// Demo players data organized by category
const DEMO_PLAYERS: Player[] = [
  // ============================================
  // 2025 SEAHAWKS - Super Bowl LX Roster (24 players)
  // ============================================
  // OFFENSE
  {
    id: '2025-sea-sam-darnold',
    name: 'Sam Darnold',
    jersey_number: 14,
    position: 'Quarterback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3912547.png',
    stats: { 'Pass Yds': '4,048', 'Pass TD': '25', 'Rating': '99.1' },
    bio: 'Seahawks QB - 2025 Season',
    super_bowl_highlight: 'Leading Seahawks to Super Bowl LX appearance',
    trivia: ['Led Seahawks to 14-3 record', 'Signed after breakout 2024 season in Minnesota'],
    display_order: 1,
    is_active: true,
  },
  {
    id: '2025-sea-kenneth-walker',
    name: 'Kenneth Walker III',
    jersey_number: 9,
    position: 'Running Back',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4567048.png',
    stats: { 'Rush Yds': '1,027', 'Rush TD': '9', 'Yds/Carry': '4.6' },
    bio: 'Seahawks RB1 - 2025 Season',
    super_bowl_highlight: '4 rushing TDs in final two playoff games',
    trivia: ['Rushed for over 1,000 yards in 2025', '2022 second-round pick from Michigan State'],
    display_order: 2,
    is_active: true,
  },
  {
    id: '2025-sea-zach-charbonnet',
    name: 'Zach Charbonnet',
    jersey_number: 26,
    position: 'Running Back',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4242335.png',
    stats: { 'Rush Yds': '582', 'Rush TD': '6', 'Rec Yds': '245' },
    bio: 'Seahawks RB2 - 2025 Season',
    super_bowl_highlight: 'Key short-yardage and receiving back',
    trivia: ['UCLA product drafted in 2023', 'Excellent pass blocker'],
    display_order: 3,
    is_active: true,
  },
  {
    id: '2025-sea-jaxon-smith-njigba',
    name: 'Jaxon Smith-Njigba',
    jersey_number: 11,
    position: 'Wide Receiver',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4430878.png',
    stats: { 'Rec': '119', 'Rec Yds': '1,793', 'Rec TD': '10' },
    bio: 'Seahawks WR - 2025 NFL Receiving Leader',
    super_bowl_highlight: 'Led NFL in receiving yards heading into Super Bowl',
    trivia: ['Set Seahawks single-season receiving record', '2023 first-round pick from Ohio State'],
    display_order: 4,
    is_active: true,
  },
  {
    id: '2025-sea-dk-metcalf',
    name: 'DK Metcalf',
    jersey_number: 14,
    position: 'Wide Receiver',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4047650.png',
    stats: { 'Rec': '78', 'Rec Yds': '1,087', 'Rec TD': '8' },
    bio: 'Seahawks WR - Deep Threat',
    super_bowl_highlight: 'Dominant red zone target with 8 TDs',
    trivia: ['6-foot-4 with 4.33 speed', 'Known for chasedown tackle in 2020'],
    display_order: 5,
    is_active: true,
  },
  {
    id: '2025-sea-tyler-lockett',
    name: 'Tyler Lockett',
    jersey_number: 16,
    position: 'Wide Receiver',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/2577327.png',
    stats: { 'Rec': '62', 'Rec Yds': '758', 'Rec TD': '5' },
    bio: 'Seahawks WR - Veteran Leader',
    super_bowl_highlight: 'Clutch third-down receptions in playoffs',
    trivia: ['10th season with Seahawks', 'Kansas State legend'],
    display_order: 6,
    is_active: true,
  },
  {
    id: '2025-sea-noah-fant',
    name: 'Noah Fant',
    jersey_number: 87,
    position: 'Tight End',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4035687.png',
    stats: { 'Rec': '48', 'Rec Yds': '526', 'Rec TD': '4' },
    bio: 'Seahawks TE - 2025 Season',
    super_bowl_highlight: 'Key middle-of-field target',
    trivia: ['Acquired in Russell Wilson trade', 'Iowa product with elite athleticism'],
    display_order: 7,
    is_active: true,
  },
  {
    id: '2025-sea-charles-cross',
    name: 'Charles Cross',
    jersey_number: 67,
    position: 'Offensive Tackle',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4426354.png',
    stats: { 'Sacks Allowed': '3', 'Pressures': '18', 'Grade': '82.4' },
    bio: 'Seahawks LT - 2025 Season',
    super_bowl_highlight: 'Protecting Darnold\'s blind side',
    trivia: ['2022 first-round pick', 'Mississippi State standout'],
    display_order: 8,
    is_active: true,
  },
  {
    id: '2025-sea-laken-tomlinson',
    name: 'Laken Tomlinson',
    jersey_number: 75,
    position: 'Guard',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/2576414.png',
    stats: { 'Sacks Allowed': '1', 'Penalties': '3', 'Grade': '78.2' },
    bio: 'Seahawks LG - 2025 Season',
    super_bowl_highlight: 'Veteran leadership on the line',
    trivia: ['Pro Bowl selection in 2021', 'Duke product'],
    display_order: 9,
    is_active: true,
  },
  {
    id: '2025-sea-olu-oluwatimi',
    name: 'Olu Oluwatimi',
    jersey_number: 65,
    position: 'Center',
    image_url: null,
    stats: { 'Snaps': '1,088', 'Sacks Allowed': '0', 'Grade': '75.8' },
    bio: 'Seahawks C - 2025 Season',
    super_bowl_highlight: 'Anchoring the offensive line',
    trivia: ['2023 Rimington Trophy winner at Michigan', 'Graduate transfer success story'],
    display_order: 10,
    is_active: true,
  },
  {
    id: '2025-sea-anthony-bradford',
    name: 'Anthony Bradford',
    jersey_number: 73,
    position: 'Guard',
    image_url: null,
    stats: { 'Sacks Allowed': '2', 'Penalties': '4', 'Grade': '72.1' },
    bio: 'Seahawks RG - 2025 Season',
    super_bowl_highlight: 'Power run blocking specialist',
    trivia: ['LSU product', 'Known for nasty streak'],
    display_order: 11,
    is_active: true,
  },
  {
    id: '2025-sea-abraham-lucas',
    name: 'Abraham Lucas',
    jersey_number: 72,
    position: 'Offensive Tackle',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4361741.png',
    stats: { 'Sacks Allowed': '4', 'Pressures': '22', 'Grade': '76.5' },
    bio: 'Seahawks RT - 2025 Season',
    super_bowl_highlight: 'Returned strong from 2024 knee injury',
    trivia: ['Washington State product', '2022 third-round pick'],
    display_order: 12,
    is_active: true,
  },
  // DEFENSE
  {
    id: '2025-sea-leonard-williams',
    name: 'Leonard Williams',
    jersey_number: 99,
    position: 'Defensive End',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/2976212.png',
    stats: { 'Sacks': '9.5', 'Tackles': '58', 'TFL': '12' },
    bio: 'Seahawks DE - 2025 Season',
    super_bowl_highlight: 'Dominant interior pass rusher',
    trivia: ['2-time Pro Bowl selection', 'USC product'],
    display_order: 13,
    is_active: true,
  },
  {
    id: '2025-sea-jarran-reed',
    name: 'Jarran Reed',
    jersey_number: 90,
    position: 'Defensive Tackle',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3054850.png',
    stats: { 'Sacks': '5.5', 'Tackles': '42', 'TFL': '8' },
    bio: 'Seahawks DT - 2025 Season',
    super_bowl_highlight: 'Run-stuffing anchor',
    trivia: ['Alabama national champion', 'Returned to Seattle in 2023'],
    display_order: 14,
    is_active: true,
  },
  {
    id: '2025-sea-dre-mont-jones',
    name: 'Dre\'Mont Jones',
    jersey_number: 93,
    position: 'Defensive End',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3916387.png',
    stats: { 'Sacks': '7.0', 'Tackles': '45', 'TFL': '10' },
    bio: 'Seahawks DE - 2025 Season',
    super_bowl_highlight: 'Versatile interior defender',
    trivia: ['Ohio State product', 'Signed from Denver in 2023'],
    display_order: 15,
    is_active: true,
  },
  {
    id: '2025-sea-boye-mafe',
    name: 'Boye Mafe',
    jersey_number: 53,
    position: 'Edge Rusher',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4361418.png',
    stats: { 'Sacks': '11.5', 'Tackles': '48', 'FF': '3' },
    bio: 'Seahawks EDGE - 2025 Pro Bowl',
    super_bowl_highlight: 'Breakout pass rusher with double-digit sacks',
    trivia: ['Minnesota product', '2022 second-round pick'],
    display_order: 16,
    is_active: true,
  },
  {
    id: '2025-sea-tyrel-dodson',
    name: 'Tyrel Dodson',
    jersey_number: 51,
    position: 'Linebacker',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3921688.png',
    stats: { 'Tackles': '124', 'Sacks': '2.5', 'INT': '2' },
    bio: 'Seahawks LB - Defensive Captain',
    super_bowl_highlight: 'Leading tackler and signal caller',
    trivia: ['Texas A&M product', 'Team defensive leader'],
    display_order: 17,
    is_active: true,
  },
  {
    id: '2025-sea-jerome-baker',
    name: 'Jerome Baker',
    jersey_number: 56,
    position: 'Linebacker',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3116365.png',
    stats: { 'Tackles': '98', 'Sacks': '3.0', 'Pass Def': '6' },
    bio: 'Seahawks LB - 2025 Season',
    super_bowl_highlight: 'Coverage linebacker excellence',
    trivia: ['Ohio State product', 'Formerly with Miami Dolphins'],
    display_order: 18,
    is_active: true,
  },
  {
    id: '2025-sea-devon-witherspoon',
    name: 'Devon Witherspoon',
    jersey_number: 21,
    position: 'Cornerback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4429013.png',
    stats: { 'Tackles': '68', 'INT': '4', 'Pass Def': '16' },
    bio: 'Seahawks CB - 2025 All-Pro',
    super_bowl_highlight: 'Shutdown corner allowing lowest passer rating',
    trivia: ['2023 DROY finalist', 'Illinois product'],
    display_order: 19,
    is_active: true,
  },
  {
    id: '2025-sea-riq-woolen',
    name: 'Riq Woolen',
    jersey_number: 27,
    position: 'Cornerback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4379394.png',
    stats: { 'Tackles': '52', 'INT': '3', 'Pass Def': '12' },
    bio: 'Seahawks CB - 2025 Season',
    super_bowl_highlight: 'Ball-hawking corner with elite length',
    trivia: ['6-foot-4 with 4.26 speed', 'UTSA product'],
    display_order: 20,
    is_active: true,
  },
  {
    id: '2025-sea-julian-love',
    name: 'Julian Love',
    jersey_number: 37,
    position: 'Safety',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3929856.png',
    stats: { 'Tackles': '89', 'INT': '3', 'Pass Def': '8' },
    bio: 'Seahawks S - 2025 Season',
    super_bowl_highlight: 'Versatile safety making impact plays',
    trivia: ['Notre Dame product', 'Signed from Giants in 2023'],
    display_order: 21,
    is_active: true,
  },
  {
    id: '2025-sea-rayshawn-jenkins',
    name: 'Rayshawn Jenkins',
    jersey_number: 2,
    position: 'Safety',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/2979501.png',
    stats: { 'Tackles': '76', 'INT': '2', 'FF': '2' },
    bio: 'Seahawks S - 2025 Season',
    super_bowl_highlight: 'Hard-hitting enforcer in secondary',
    trivia: ['Miami (FL) product', 'Veteran leader'],
    display_order: 22,
    is_active: true,
  },
  // SPECIAL TEAMS
  {
    id: '2025-sea-jason-myers',
    name: 'Jason Myers',
    jersey_number: 5,
    position: 'Kicker',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/2515934.png',
    stats: { 'FG%': '92.3%', 'FG Made': '24/26', 'Long': '56' },
    bio: 'Seahawks K - 2025 Season',
    super_bowl_highlight: 'Automatic from 50+ yards',
    trivia: ['Pro Bowl selection in 2018', 'Marist College product'],
    display_order: 23,
    is_active: true,
  },
  {
    id: '2025-sea-michael-dickson',
    name: 'Michael Dickson',
    jersey_number: 4,
    position: 'Punter',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3122899.png',
    stats: { 'Avg': '48.2', 'Net': '44.1', 'Inside 20': '28' },
    bio: 'Seahawks P - 2025 Pro Bowl',
    super_bowl_highlight: 'Elite punter flipping field position',
    trivia: ['2018 Ray Guy Award winner', 'Australian-born'],
    display_order: 24,
    is_active: true,
  },
  // COACHING STAFF
  {
    id: '2025-sea-mike-macdonald',
    name: 'Mike Macdonald',
    jersey_number: 0,
    position: 'Head Coach',
    image_url: null,
    stats: { 'Record': '14-3', 'NFC Seed': '1st', 'Division': 'NFC West' },
    bio: 'Seahawks Head Coach - 2nd Year',
    super_bowl_highlight: 'Youngest HC to lead team to Super Bowl since Sean McVay',
    trivia: ['9th head coach in franchise history', 'Former Ravens DC'],
    display_order: 25,
    is_active: true,
  },
  {
    id: '2025-sea-klint-kubiak',
    name: 'Klint Kubiak',
    jersey_number: 0,
    position: 'Offensive Coordinator',
    image_url: null,
    stats: { 'Points/Game': '28.4', 'NFL Rank': '3rd', 'Pass Yds': '4,048' },
    bio: 'Seahawks OC - 2025 Season',
    super_bowl_highlight: 'Designed offense that maximized Darnold\'s abilities',
    trivia: ['Son of Super Bowl champion Gary Kubiak', 'Former Vikings OC'],
    display_order: 26,
    is_active: true,
  },
  {
    id: '2025-sea-aden-durde',
    name: 'Aden Durde',
    jersey_number: 0,
    position: 'Defensive Coordinator',
    image_url: null,
    stats: { 'Points Allowed': '17.2', 'NFL Rank': '1st', 'Sacks': '48' },
    bio: 'Seahawks DC - 2025 Season',
    super_bowl_highlight: 'Led NFL\'s #1 scoring defense',
    trivia: ['British-born coach', 'Former Cowboys DC'],
    display_order: 27,
    is_active: true,
  },
  {
    id: '2025-sea-leslie-frazier',
    name: 'Leslie Frazier',
    jersey_number: 0,
    position: 'Assistant Head Coach',
    image_url: null,
    stats: { 'HC Experience': '4 years', 'DC Experience': '10+ years', 'Super Bowls': '1 (player)' },
    bio: 'Seahawks Assistant HC - 2025 Season',
    super_bowl_highlight: 'Veteran leadership and defensive expertise',
    trivia: ['Former Vikings head coach', 'Won Super Bowl XX as player'],
    display_order: 28,
    is_active: true,
  },
  {
    id: '2025-sea-john-schneider',
    name: 'John Schneider',
    jersey_number: 0,
    position: 'General Manager',
    image_url: null,
    stats: { 'Tenure': '16 years', 'Super Bowls': '1 (XLVIII)', 'Draft Picks': '100+' },
    bio: 'Seahawks GM - Architect of Dynasty',
    super_bowl_highlight: 'Built both Super Bowl XLVIII and LX rosters',
    trivia: ['Longest-tenured GM in NFL', 'Traded for Sam Darnold in 2025'],
    display_order: 29,
    is_active: true,
  },
  // ============================================
  // 2025 PATRIOTS - Super Bowl LX Opponent (24 players)
  // ============================================
  // OFFENSE
  {
    id: '2025-pats-drake-maye',
    name: 'Drake Maye',
    jersey_number: 10,
    position: 'Quarterback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4432577.png',
    stats: { 'Pass Yds': '3,892', 'Pass TD': '28', 'Rating': '96.4' },
    bio: 'Patriots QB - 2025 Season',
    super_bowl_highlight: 'Led Patriots to Super Bowl in sophomore season',
    trivia: ['2024 first-round pick from North Carolina', 'Youngest QB in franchise history to start Super Bowl'],
    display_order: 101,
    is_active: true,
  },
  {
    id: '2025-pats-rhamondre-stevenson',
    name: 'Rhamondre Stevenson',
    jersey_number: 38,
    position: 'Running Back',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4259545.png',
    stats: { 'Rush Yds': '1,156', 'Rush TD': '8', 'Rec Yds': '421' },
    bio: 'Patriots RB1 - 2025 Season',
    super_bowl_highlight: 'Workhorse back powering Patriots playoff run',
    trivia: ['Oklahoma product', 'Elite pass-catching running back'],
    display_order: 102,
    is_active: true,
  },
  {
    id: '2025-pats-treveyon-henderson',
    name: 'TreVeyon Henderson',
    jersey_number: 32,
    position: 'Running Back',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4567156.png',
    stats: { 'Rush Yds': '687', 'Rush TD': '6', 'Rec Yds': '289' },
    bio: 'Patriots RB2 - 2025 Rookie',
    super_bowl_highlight: 'Explosive rookie making playoff impact',
    trivia: ['2025 second-round pick from Ohio State', 'Elite speed and burst'],
    display_order: 103,
    is_active: true,
  },
  {
    id: '2025-pats-ja-lynn-polk',
    name: 'Ja\'Lynn Polk',
    jersey_number: 1,
    position: 'Wide Receiver',
    image_url: null,
    stats: { 'Rec': '72', 'Rec Yds': '1,012', 'Rec TD': '7' },
    bio: 'Patriots WR1 - 2025 Season',
    super_bowl_highlight: 'Rookie breakout with 1,000+ yards',
    trivia: ['2024 second-round pick from Washington', 'Deep threat specialist'],
    display_order: 104,
    is_active: true,
  },
  {
    id: '2025-pats-demario-douglas',
    name: 'DeMario Douglas',
    jersey_number: 3,
    position: 'Wide Receiver',
    image_url: null,
    stats: { 'Rec': '68', 'Rec Yds': '824', 'Rec TD': '5' },
    bio: 'Patriots WR2 - 2025 Season',
    super_bowl_highlight: 'Slot receiver with elite quickness',
    trivia: ['Liberty product', 'Led team in receptions as rookie in 2023'],
    display_order: 105,
    is_active: true,
  },
  {
    id: '2025-pats-stefon-diggs',
    name: 'Stefon Diggs',
    jersey_number: 8,
    position: 'Wide Receiver',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/16460.png',
    stats: { 'Rec': '92', 'Rec Yds': '1,156', 'Rec TD': '9' },
    bio: 'Patriots WR1 - 2025 Free Agent Signing',
    super_bowl_highlight: 'Veteran playmaker leading receiving corps',
    trivia: ['4-time Pro Bowl selection', 'Signed from Houston in 2025 free agency'],
    display_order: 106,
    is_active: true,
  },
  {
    id: '2025-pats-hunter-henry',
    name: 'Hunter Henry',
    jersey_number: 85,
    position: 'Tight End',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3051889.png',
    stats: { 'Rec': '58', 'Rec Yds': '642', 'Rec TD': '6' },
    bio: 'Patriots TE - 2025 Season',
    super_bowl_highlight: 'Red zone weapon with sure hands',
    trivia: ['Arkansas product', '2016 second-round pick'],
    display_order: 107,
    is_active: true,
  },
  {
    id: '2025-pats-caedan-wallace',
    name: 'Caedan Wallace',
    jersey_number: 76,
    position: 'Offensive Tackle',
    image_url: null,
    stats: { 'Sacks Allowed': '4', 'Pressures': '24', 'Grade': '74.8' },
    bio: 'Patriots LT - 2025 Season',
    super_bowl_highlight: 'Protecting Maye\'s blind side',
    trivia: ['Penn State product', '2024 third-round pick'],
    display_order: 108,
    is_active: true,
  },
  {
    id: '2025-pats-cole-strange',
    name: 'Cole Strange',
    jersey_number: 69,
    position: 'Guard',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4036348.png',
    stats: { 'Sacks Allowed': '1', 'Penalties': '3', 'Grade': '79.2' },
    bio: 'Patriots LG - 2025 Season',
    super_bowl_highlight: 'Mauling run blocker',
    trivia: ['Chattanooga product', '2022 first-round pick'],
    display_order: 109,
    is_active: true,
  },
  {
    id: '2025-pats-david-andrews',
    name: 'David Andrews',
    jersey_number: 60,
    position: 'Center',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/2577134.png',
    stats: { 'Snaps': '1,105', 'Sacks Allowed': '1', 'Grade': '82.1' },
    bio: 'Patriots C - Team Captain',
    super_bowl_highlight: 'Veteran leader and line anchor',
    trivia: ['Georgia product', 'Undrafted success story'],
    display_order: 110,
    is_active: true,
  },
  {
    id: '2025-pats-mike-onwenu',
    name: 'Mike Onwenu',
    jersey_number: 71,
    position: 'Guard',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3915483.png',
    stats: { 'Sacks Allowed': '2', 'Penalties': '2', 'Grade': '81.4' },
    bio: 'Patriots RG - 2025 Season',
    super_bowl_highlight: 'Elite pass protector',
    trivia: ['Michigan product', 'Pro Bowl caliber'],
    display_order: 111,
    is_active: true,
  },
  {
    id: '2025-pats-vederian-lowe',
    name: 'Vederian Lowe',
    jersey_number: 73,
    position: 'Offensive Tackle',
    image_url: null,
    stats: { 'Sacks Allowed': '5', 'Pressures': '28', 'Grade': '71.2' },
    bio: 'Patriots RT - 2025 Season',
    super_bowl_highlight: 'Physical run blocker on right side',
    trivia: ['Illinois product', 'Started all 17 games'],
    display_order: 112,
    is_active: true,
  },
  // DEFENSE
  {
    id: '2025-pats-keion-white',
    name: 'Keion White',
    jersey_number: 94,
    position: 'Defensive End',
    image_url: null,
    stats: { 'Sacks': '10.5', 'Tackles': '52', 'TFL': '14' },
    bio: 'Patriots DE - 2025 Breakout Star',
    super_bowl_highlight: 'Elite pass rusher with double-digit sacks',
    trivia: ['Georgia Tech product', '2023 second-round pick'],
    display_order: 113,
    is_active: true,
  },
  {
    id: '2025-pats-davon-godchaux',
    name: 'Davon Godchaux',
    jersey_number: 92,
    position: 'Defensive Tackle',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3052897.png',
    stats: { 'Sacks': '3.5', 'Tackles': '48', 'TFL': '9' },
    bio: 'Patriots DT - 2025 Season',
    super_bowl_highlight: 'Run-stuffing nose tackle',
    trivia: ['LSU product', 'Signed from Miami in 2021'],
    display_order: 114,
    is_active: true,
  },
  {
    id: '2025-pats-christian-barmore',
    name: 'Christian Barmore',
    jersey_number: 90,
    position: 'Defensive Tackle',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4360238.png',
    stats: { 'Sacks': '6.0', 'Tackles': '38', 'TFL': '11' },
    bio: 'Patriots DT - 2025 Season',
    super_bowl_highlight: 'Interior pass rush dominance',
    trivia: ['Alabama product', '2021 second-round pick'],
    display_order: 115,
    is_active: true,
  },
  {
    id: '2025-pats-harold-landry',
    name: 'Harold Landry III',
    jersey_number: 58,
    position: 'Edge Rusher',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3116593.png',
    stats: { 'Sacks': '11.0', 'Tackles': '56', 'FF': '4' },
    bio: 'Patriots EDGE - 2025 Free Agent Signing',
    super_bowl_highlight: 'Elite pass rusher anchoring defense',
    trivia: ['Former Titans standout', 'Signed $87M deal in 2025 free agency'],
    display_order: 116,
    is_active: true,
  },
  {
    id: '2025-pats-ja-whaun-bentley',
    name: 'Ja\'Whaun Bentley',
    jersey_number: 8,
    position: 'Linebacker',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3116158.png',
    stats: { 'Tackles': '118', 'Sacks': '2.0', 'INT': '1' },
    bio: 'Patriots LB - Team Captain',
    super_bowl_highlight: 'Defensive signal caller and tackle leader',
    trivia: ['Purdue product', 'Team leader in tackles'],
    display_order: 117,
    is_active: true,
  },
  {
    id: '2025-pats-robert-spillane',
    name: 'Robert Spillane',
    jersey_number: 41,
    position: 'Linebacker',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3128724.png',
    stats: { 'Tackles': '102', 'Sacks': '3.0', 'INT': '2' },
    bio: 'Patriots LB - 2025 Free Agent Signing',
    super_bowl_highlight: 'Physical run-stopping linebacker',
    trivia: ['Former Raiders standout', 'Signed from Las Vegas in 2025'],
    display_order: 118,
    is_active: true,
  },
  {
    id: '2025-pats-christian-gonzalez',
    name: 'Christian Gonzalez',
    jersey_number: 0,
    position: 'Cornerback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4426354.png',
    stats: { 'Tackles': '58', 'INT': '5', 'Pass Def': '14' },
    bio: 'Patriots CB - 2025 All-Pro',
    super_bowl_highlight: 'Elite shutdown corner anchoring secondary',
    trivia: ['Oregon product', '2023 first-round pick'],
    display_order: 119,
    is_active: true,
  },
  {
    id: '2025-pats-carlton-davis',
    name: 'Carlton Davis III',
    jersey_number: 24,
    position: 'Cornerback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3121427.png',
    stats: { 'Tackles': '54', 'INT': '4', 'Pass Def': '12' },
    bio: 'Patriots CB - 2025 Free Agent Signing',
    super_bowl_highlight: 'Physical press corner shutting down receivers',
    trivia: ['Former Buccaneers standout', 'Won Super Bowl LV with Tampa Bay'],
    display_order: 120,
    is_active: true,
  },
  {
    id: '2025-pats-kyle-dugger',
    name: 'Kyle Dugger',
    jersey_number: 23,
    position: 'Safety',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4035222.png',
    stats: { 'Tackles': '92', 'INT': '3', 'Sacks': '2.0' },
    bio: 'Patriots S - 2025 Pro Bowl',
    super_bowl_highlight: 'Hard-hitting safety and team leader',
    trivia: ['Lenoir-Rhyne product', '2020 second-round pick'],
    display_order: 121,
    is_active: true,
  },
  {
    id: '2025-pats-jabrill-peppers',
    name: 'Jabrill Peppers',
    jersey_number: 3,
    position: 'Safety',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3052896.png',
    stats: { 'Tackles': '78', 'INT': '2', 'FF': '2' },
    bio: 'Patriots S - 2025 Season',
    super_bowl_highlight: 'Versatile safety with big-play ability',
    trivia: ['Michigan product', 'Former first-round pick'],
    display_order: 122,
    is_active: true,
  },
  // SPECIAL TEAMS
  {
    id: '2025-pats-joey-slye',
    name: 'Joey Slye',
    jersey_number: 6,
    position: 'Kicker',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3051302.png',
    stats: { 'FG%': '88.5%', 'FG Made': '23/26', 'Long': '58' },
    bio: 'Patriots K - 2025 Season',
    super_bowl_highlight: 'Big leg and clutch performer',
    trivia: ['Virginia Tech product', 'Known for 50+ yard range'],
    display_order: 123,
    is_active: true,
  },
  {
    id: '2025-pats-bryce-baringer',
    name: 'Bryce Baringer',
    jersey_number: 17,
    position: 'Punter',
    image_url: null,
    stats: { 'Avg': '47.8', 'Net': '43.2', 'Inside 20': '24' },
    bio: 'Patriots P - 2025 Season',
    super_bowl_highlight: 'Elite hang time and directional punting',
    trivia: ['Michigan State product', '2023 sixth-round pick'],
    display_order: 124,
    is_active: true,
  },
  // COACHING STAFF
  {
    id: '2025-pats-mike-vrabel',
    name: 'Mike Vrabel',
    jersey_number: 0,
    position: 'Head Coach',
    image_url: null,
    stats: { 'Record': '14-3', 'AFC Seed': '1st', 'Division': 'AFC East' },
    bio: 'Patriots Head Coach - 1st Year',
    super_bowl_highlight: 'Return to New England where he won 3 Super Bowls as player',
    trivia: ['Won 3 Super Bowls as Patriots LB', 'Former Titans head coach'],
    display_order: 125,
    is_active: true,
  },
  {
    id: '2025-pats-josh-mcdaniels',
    name: 'Josh McDaniels',
    jersey_number: 0,
    position: 'Offensive Coordinator',
    image_url: null,
    stats: { 'Points/Game': '28.8', 'NFL Rank': '2nd', 'Pass Yds': '3,892' },
    bio: 'Patriots OC - 2025 Season',
    super_bowl_highlight: 'Reunited with Patriots to develop Drake Maye',
    trivia: ['6-time Super Bowl champion as coordinator', 'Returned to New England in 2025'],
    display_order: 126,
    is_active: true,
  },
  {
    id: '2025-pats-terrell-williams',
    name: 'Terrell Williams',
    jersey_number: 0,
    position: 'Defensive Coordinator',
    image_url: null,
    stats: { 'Points Allowed': '18.8', 'NFL Rank': '4th', 'Takeaways': '28' },
    bio: 'Patriots DC - 2025 Season',
    super_bowl_highlight: 'Aggressive defense creating turnovers',
    trivia: ['Former Chargers DC', 'Known for creative blitz packages'],
    display_order: 127,
    is_active: true,
  },
  {
    id: '2025-pats-eliot-wolf',
    name: 'Eliot Wolf',
    jersey_number: 0,
    position: 'General Manager',
    image_url: null,
    stats: { 'FA Signings': '$360M', 'Draft': 'Campbell, Henderson', 'Record': '14-3' },
    bio: 'Patriots GM - 2025 Season',
    super_bowl_highlight: 'Assembled roster through aggressive free agency',
    trivia: ['Son of former Packers GM Ron Wolf', 'Key signings: Diggs, Landry, Davis'],
    display_order: 128,
    is_active: true,
  },
  // ============================================
  // SUPER BOWL XLVIII HEROES (6 players)
  // ============================================
  {
    id: 'sbxlviii-russell-wilson',
    name: 'Russell Wilson',
    jersey_number: 3,
    position: 'Quarterback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/14881.png',
    stats: { 'Pass Yds': '206', 'Pass TD': '2', 'Rating': '123.1' },
    bio: 'Super Bowl XLVIII Champion QB',
    super_bowl_highlight: 'Led the Seahawks to a 43-8 victory in Super Bowl XLVIII',
    trivia: ['Became 2nd Black QB to win a Super Bowl', 'Led game-opening 80-yard TD drive'],
    display_order: 201,
    is_active: false,
  },
  {
    id: 'sbxlviii-marshawn-lynch',
    name: 'Marshawn Lynch',
    jersey_number: 24,
    position: 'Running Back',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/10456.png',
    stats: { 'Rush Yds': '39', 'Rush TD': '1', 'Carries': '15' },
    bio: 'Super Bowl XLVIII Champion RB - Beast Mode',
    super_bowl_highlight: 'Beast Mode touchdown run in Super Bowl XLVIII',
    trivia: ['Scored Seahawks first Super Bowl TD', 'Famous Beast Quake run in 2011 playoffs'],
    display_order: 202,
    is_active: false,
  },
  {
    id: 'sbxlviii-richard-sherman',
    name: 'Richard Sherman',
    jersey_number: 25,
    position: 'Cornerback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/14086.png',
    stats: { 'Tackles': '3', 'Pass Def': '2', 'Pro Bowls': '5' },
    bio: 'Legion of Boom - All-Pro Corner',
    super_bowl_highlight: 'Key interception sealing NFC Championship',
    trivia: ['3-time First-Team All-Pro', 'Stanford graduate'],
    display_order: 203,
    is_active: false,
  },
  {
    id: 'sbxlviii-malcolm-smith',
    name: 'Malcolm Smith',
    jersey_number: 53,
    position: 'Linebacker',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/15116.png',
    stats: { 'Tackles': '10', 'INT': '1', 'INT TD': '1' },
    bio: 'Super Bowl XLVIII MVP',
    super_bowl_highlight: 'Super Bowl XLVIII MVP with pick-six',
    trivia: ['Returned interception 69 yards for TD', 'Also recovered a fumble'],
    display_order: 204,
    is_active: false,
  },
  {
    id: 'sbxlviii-earl-thomas',
    name: 'Earl Thomas',
    jersey_number: 29,
    position: 'Safety',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/13251.png',
    stats: { 'Tackles': '5', 'Pass Def': '2', 'Pro Bowls': '7' },
    bio: 'Legion of Boom - Elite Free Safety',
    super_bowl_highlight: 'Legion of Boom leader, 2 interceptions in playoffs',
    trivia: ['3-time First-Team All-Pro', 'Fastest safety in LOB'],
    display_order: 205,
    is_active: false,
  },
  {
    id: 'sbxlviii-kam-chancellor',
    name: 'Kam Chancellor',
    jersey_number: 31,
    position: 'Safety',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/13722.png',
    stats: { 'Tackles': '7', 'FF': '1', 'Pass Def': '1' },
    bio: 'Legion of Boom - The Enforcer',
    super_bowl_highlight: 'Devastating hits and forced fumbles',
    trivia: ['Known as Bam Bam Kam', '4-time Pro Bowl selection'],
    display_order: 206,
    is_active: false,
  },
  // ============================================
  // HALL OF FAME LEGENDS (3 players)
  // ============================================
  {
    id: 'hof-steve-largent',
    name: 'Steve Largent',
    jersey_number: 80,
    position: 'Wide Receiver',
    image_url: 'https://www.profootballhof.com/pfhof/media/Default/Items/Largent_Steve_HS_150.jpg',
    stats: { 'HOF Class': '1995', 'Career Rec': '819', 'Career TD': '100' },
    bio: 'Seahawks Legend - Hall of Fame (1995)',
    super_bowl_highlight: 'Franchise icon before Super Bowl era',
    trivia: ['First Seahawk in Hall of Fame', 'Played 14 years with Seattle'],
    display_order: 301,
    is_active: false,
  },
  {
    id: 'hof-walter-jones',
    name: 'Walter Jones',
    jersey_number: 71,
    position: 'Offensive Tackle',
    image_url: 'https://www.profootballhof.com/pfhof/media/Default/Items/Jones_Walter_HS-Capsule.jpg',
    stats: { 'HOF Class': '2014', 'Pro Bowls': '9', 'All-Pro': '4x' },
    bio: 'Seahawks Legend - Hall of Fame (2014)',
    super_bowl_highlight: 'Protected QBs for 13 seasons',
    trivia: ['One of greatest LTs ever', 'Only 23 sacks allowed in career'],
    display_order: 302,
    is_active: false,
  },
  {
    id: 'hof-cortez-kennedy',
    name: 'Cortez Kennedy',
    jersey_number: 96,
    position: 'Defensive Tackle',
    image_url: 'https://www.profootballhof.com/pfhof/media/Default/Items/Kennedy_Cortez_Action_Bio.jpg',
    stats: { 'HOF Class': '2012', 'Pro Bowls': '8', 'Sacks': '58' },
    bio: 'Seahawks Legend - Hall of Fame (2012)',
    super_bowl_highlight: 'Franchise defensive star',
    trivia: ['1992 NFL Defensive Player of the Year', '8-time Pro Bowl selection'],
    display_order: 303,
    is_active: false,
  },
]

// Filter players by category using display_order ranges and is_active flag
// Database structure:
// - 2025 Seahawks: is_active = true, display_order 1-30
// - 2025 Patriots: is_active = true, display_order 100-130
// - Super Bowl XLVIII Heroes: is_active = false, display_order 200-220
// - Hall of Fame: is_active = false, display_order 300-320
function filterByCategory(players: Player[], category: PlayerCategory): Player[] {
  switch (category) {
    case 'sb48':
      return players.filter(p => !p.is_active && p.display_order >= 200 && p.display_order < 250)
    case '2025-hawks':
      return players.filter(p => p.is_active === true && p.display_order >= 1 && p.display_order < 50)
    case '2025-pats':
      return players.filter(p => p.is_active === true && p.display_order >= 100 && p.display_order < 150)
    case 'hof':
      return players.filter(p => !p.is_active && p.display_order >= 300 && p.display_order < 350)
    case 'all':
    default:
      return players
  }
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const position = searchParams.get('position')
    const category = (searchParams.get('category') || 'sb48') as PlayerCategory

    const supabase = getSupabase()

    // Demo mode
    if (!supabase) {
      let players = filterByCategory([...DEMO_PLAYERS], category)

      if (position && position !== 'all') {
        players = players.filter(p =>
          p.position.toLowerCase().includes(position.toLowerCase())
        )
      }

      // Sort by display_order
      players.sort((a, b) => a.display_order - b.display_order)

      return NextResponse.json({
        players,
        total: players.length,
        category,
      })
    }

    // Build query - get all players (we'll filter by category)
    let query = supabase
      .from('players')
      .select('*')
      .order('display_order', { ascending: true })

    if (position && position !== 'all') {
      query = query.ilike('position', `%${position}%`)
    }

    const { data: allPlayers, error } = await query

    if (error) {
      console.error('Players fetch error:', error)
      return NextResponse.json(
        { error: 'Failed to fetch players' },
        { status: 500 }
      )
    }

    // Filter by category
    const players = filterByCategory(allPlayers || [], category)

    return NextResponse.json({
      players,
      total: players.length,
      category,
    })

  } catch (error) {
    console.error('Players error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
