import { AVATARS, type AvatarId } from './database.types'

// Re-export avatars for components
export const teamAvatars = Object.values(AVATARS).map(avatar => ({
  id: avatar.id as AvatarId,
  name: avatar.name,
  emoji: avatar.emoji,
}))

// Suggested team names for quick selection
export const suggestedTeamNames = [
  'Legion of Boom',
  '12th Man Legends',
  'Sea Hawks Rising',
  'Beast Mode',
  'Blue Thunder',
  'Hawk Nation',
  'The 12s',
  'Super Bowl Champs',
]

// Available question categories for daily rounds
export const questionCategories = [
  'Super Bowl XLVIII',
  'Legion of Boom',
  'Russell Wilson Era',
  'Seahawks Legends',
  'Stadium & 12s',
  'Memorable Moments',
  'Players & Numbers',
  'Seahawks History',
]

// Demo questions (used when Supabase not configured)
// Organized by category for easy filtering
export const sampleQuestions = [
  // Super Bowl XLVIII
  {
    id: 'demo-1',
    question_text: 'What year did the Seattle Seahawks win their first Super Bowl?',
    option_a: '2012',
    option_b: '2013',
    option_c: '2014',
    option_d: '2015',
    correct_answer: 'c' as const,
    hint_text: 'Super Bowl XLVIII was played on February 2, 2014',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Super Bowl XLVIII',
  },
  {
    id: 'demo-2',
    question_text: 'Who was named MVP of Super Bowl XLVIII?',
    option_a: 'Russell Wilson',
    option_b: 'Marshawn Lynch',
    option_c: 'Malcolm Smith',
    option_d: 'Richard Sherman',
    correct_answer: 'c' as const,
    hint_text: 'He had a pick-six',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Super Bowl XLVIII',
  },
  {
    id: 'demo-3',
    question_text: 'What was the final score of Super Bowl XLVIII?',
    option_a: '43-8',
    option_b: '34-7',
    option_c: '38-10',
    option_d: '41-14',
    correct_answer: 'a' as const,
    hint_text: 'It was the largest margin in Super Bowl history at the time',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Super Bowl XLVIII',
  },
  {
    id: 'demo-4',
    question_text: 'Which team did the Seahawks defeat in Super Bowl XLVIII?',
    option_a: 'New England Patriots',
    option_b: 'San Francisco 49ers',
    option_c: 'Denver Broncos',
    option_d: 'Green Bay Packers',
    correct_answer: 'c' as const,
    hint_text: 'They had the #1 offense that year',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Super Bowl XLVIII',
  },
  {
    id: 'demo-5',
    question_text: 'Who returned an interception for a touchdown in Super Bowl XLVIII?',
    option_a: 'Richard Sherman',
    option_b: 'Earl Thomas',
    option_c: 'Malcolm Smith',
    option_d: 'Kam Chancellor',
    correct_answer: 'c' as const,
    hint_text: 'He was also the MVP',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Super Bowl XLVIII',
  },
  // Legion of Boom
  {
    id: 'demo-6',
    question_text: 'What was the nickname of the Seahawks legendary defense?',
    option_a: 'Steel Curtain',
    option_b: 'Legion of Boom',
    option_c: 'Purple People Eaters',
    option_d: 'Monsters of the Midway',
    correct_answer: 'b' as const,
    hint_text: 'It references their big hits',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Legion of Boom',
  },
  {
    id: 'demo-7',
    question_text: 'Which three players formed the core of the Legion of Boom secondary?',
    option_a: 'Sherman, Thomas, Chancellor',
    option_b: 'Sherman, Thomas, Maxwell',
    option_c: 'Chancellor, Browner, Thomas',
    option_d: 'Sherman, Chancellor, Lane',
    correct_answer: 'a' as const,
    hint_text: 'Two safeties and a cornerback',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Legion of Boom',
  },
  {
    id: 'demo-8',
    question_text: 'What position did Richard Sherman play?',
    option_a: 'Free Safety',
    option_b: 'Strong Safety',
    option_c: 'Cornerback',
    option_d: 'Linebacker',
    correct_answer: 'c' as const,
    hint_text: 'He covered receivers on the outside',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Legion of Boom',
  },
  {
    id: 'demo-9',
    question_text: 'What jersey number did Earl Thomas wear?',
    option_a: '25',
    option_b: '29',
    option_c: '31',
    option_d: '33',
    correct_answer: 'b' as const,
    hint_text: 'It is an odd number',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Legion of Boom',
  },
  {
    id: 'demo-10',
    question_text: 'Which Legion of Boom member was known for devastating hits at the line of scrimmage?',
    option_a: 'Earl Thomas',
    option_b: 'Richard Sherman',
    option_c: 'Kam Chancellor',
    option_d: 'Brandon Browner',
    correct_answer: 'c' as const,
    hint_text: 'He played strong safety',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Legion of Boom',
  },
  // Memorable Moments
  {
    id: 'demo-11',
    question_text: 'Which Seahawk had the famous "tip" play in the 2013 NFC Championship?',
    option_a: 'Earl Thomas',
    option_b: 'Richard Sherman',
    option_c: 'Kam Chancellor',
    option_d: 'Byron Maxwell',
    correct_answer: 'b' as const,
    hint_text: 'He tipped it to a teammate for the interception',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Memorable Moments',
  },
  {
    id: 'demo-12',
    question_text: 'What was the famous Marshawn Lynch run in the 2010 playoffs called?',
    option_a: 'The Run',
    option_b: 'Beast Quake',
    option_c: 'Thunder Run',
    option_d: 'Lynch Mob',
    correct_answer: 'b' as const,
    hint_text: 'Fans caused a seismic event',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Memorable Moments',
  },
  {
    id: 'demo-13',
    question_text: 'Against which team did the "Beast Quake" run occur?',
    option_a: 'Green Bay Packers',
    option_b: 'New Orleans Saints',
    option_c: 'Dallas Cowboys',
    option_d: 'Atlanta Falcons',
    correct_answer: 'b' as const,
    hint_text: 'They were the defending Super Bowl champions',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Memorable Moments',
  },
  // Players & Numbers
  {
    id: 'demo-14',
    question_text: 'What jersey number did Beast Mode Marshawn Lynch wear?',
    option_a: '20',
    option_b: '22',
    option_c: '24',
    option_d: '28',
    correct_answer: 'c' as const,
    hint_text: 'It is an even number in the 20s',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Players & Numbers',
  },
  {
    id: 'demo-15',
    question_text: 'What jersey number did Russell Wilson wear with the Seahawks?',
    option_a: '1',
    option_b: '3',
    option_c: '7',
    option_d: '12',
    correct_answer: 'b' as const,
    hint_text: 'A single digit number',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Players & Numbers',
  },
  // Seahawks History
  {
    id: 'demo-16',
    question_text: 'What year were the Seattle Seahawks founded?',
    option_a: '1974',
    option_b: '1976',
    option_c: '1978',
    option_d: '1980',
    correct_answer: 'b' as const,
    hint_text: 'During Americas bicentennial',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Seahawks History',
  },
  {
    id: 'demo-17',
    question_text: 'What division are the Seahawks currently in?',
    option_a: 'NFC West',
    option_b: 'NFC North',
    option_c: 'AFC West',
    option_d: 'NFC South',
    correct_answer: 'a' as const,
    hint_text: 'They share it with the 49ers',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Seahawks History',
  },
  {
    id: 'demo-18',
    question_text: 'How many times have the Seahawks appeared in the Super Bowl?',
    option_a: '1',
    option_b: '2',
    option_c: '3',
    option_d: '4',
    correct_answer: 'c' as const,
    hint_text: 'They won one of them',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Seahawks History',
  },
  // Seahawks Legends
  {
    id: 'demo-19',
    question_text: 'Who is the Seahawks all-time leading rusher?',
    option_a: 'Marshawn Lynch',
    option_b: 'Shaun Alexander',
    option_c: 'Chris Warren',
    option_d: 'Curt Warner',
    correct_answer: 'b' as const,
    hint_text: 'He won NFL MVP in 2005',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Seahawks Legends',
  },
  {
    id: 'demo-20',
    question_text: 'Which Seahawk won NFL MVP in 2005?',
    option_a: 'Matt Hasselbeck',
    option_b: 'Shaun Alexander',
    option_c: 'Walter Jones',
    option_d: 'Steve Largent',
    correct_answer: 'b' as const,
    hint_text: 'He was a running back',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Seahawks Legends',
  },
]

// Helper to get questions by category
export const getQuestionsByCategory = (category: string) =>
  sampleQuestions.filter(q => q.category === category)

// Demo players with full baseball card data
// Organized by: 2025 Current Roster, Super Bowl XLVIII Heroes, Hall of Fame Legends
export const samplePlayers = [
  // ============================================
  // 2025 SEAHAWKS CURRENT ROSTER
  // ============================================
  {
    id: '2025-sam-darnold',
    name: 'Sam Darnold',
    jersey_number: 14,
    position: 'Quarterback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3912547.png',
    stats: { 'Pass Yds': '4,048', 'Pass TD': '25', 'INT': '14', 'Rating': '99.1', 'Record': '14-3' },
    trivia: [
      'Led Seahawks to 14-3 record and Super Bowl LX appearance',
      'Second QB in NFL history with 14-3 record (after Tom Brady)',
      'Threw for 470 yards, 4 TDs, 0 INTs in first two playoff games',
      'Signed with Seattle after breakout 2024 season in Minnesota',
    ],
    bio: 'Seahawks QB - 2025 Season - Super Bowl LX',
    super_bowl_highlight: 'Leading Seahawks to Super Bowl LX appearance',
    display_order: 1,
    is_active: true,
    imageUrl: 'https://images.unsplash.com/photo-1761258772149-c0ba7e8db954?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhbWVyaWNhbiUyMGZvb3RiYWxsJTIwcXVhcnRlcmJhY2slMjBhY3Rpb258ZW58MXx8fHwxNzcwMTk4MTUyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'Passing Yards', value: '206' },
      { label: 'Touchdowns', value: '2' },
      { label: 'Completion %', value: '72.4%' },
      { label: 'QBR', value: '123.1' },
    ],
    superBowlHighlight: 'Led the offense with precision passing and two touchdown throws.',
    trivia: [
      'Became the 2nd Black QB to win a Super Bowl',
      'Led game-opening 80-yard TD drive in 12 plays',
      'Threw TD passes to Jermaine Kearse and Doug Baldwin',
      'At 25, one of the youngest QBs to win a championship',
    ],
  },
  {
    id: '2025-jaxon-smith-njigba',
    name: 'Jaxon Smith-Njigba',
    jersey_number: 11,
    position: 'Wide Receiver',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4430878.png',
    stats: { 'Receptions': '119', 'Rec Yds': '1,793', 'Rec TD': '10', 'Yds/Rec': '15.1' },
    trivia: [
      'Led NFL in receiving yards in 2025 with 1,793',
      'Set Seahawks franchise single-season receiving record',
      'NFC Offensive Player of the Month (October 2025)',
      'Had 10 catches for 153 yards in NFC Championship win',
    ],
    bio: 'Seahawks WR - 2025 NFL Receiving Leader',
    super_bowl_highlight: 'NFL receiving yards leader heading into Super Bowl LX',
    display_order: 2,
    is_active: true,
  },
  {
    id: '2025-kenneth-walker-iii',
    name: 'Kenneth Walker III',
    jersey_number: 9,
    position: 'Running Back',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4567048.png',
    stats: { 'Rush Yds': '1,027', 'Rush TD': '5', 'Carries': '221', 'Yds/Carry': '4.6' },
    trivia: [
      'Rushed for over 1,000 yards in 2025 regular season',
      'Career-high 1,309 scrimmage yards',
      'Had 116 rush yards and 3 TDs in Divisional Round win',
      'Became clear workhorse after Charbonnet ACL injury',
    ],
    bio: 'Seahawks RB - 2025 Workhorse Back',
    super_bowl_highlight: '4 rushing TDs in final two playoff games',
    display_order: 3,
    is_active: true,
    imageUrl: 'https://images.unsplash.com/photo-1593051531088-fd52df065aa2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMHJ1bm5pbmclMjBiYWNrJTIwYXRobGV0ZXxlbnwxfHx8fDE3NzAxOTgxNTJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'Rush Yards', value: '39' },
      { label: 'Touchdowns', value: '1' },
      { label: 'Carries', value: '15' },
      { label: 'Avg Yards', value: '2.6' },
    ],
    superBowlHighlight: 'Beast Mode powered through for a crucial touchdown run.',
    trivia: [
      'Scored on a 1-yard TD run in the 3rd quarter',
      'Beast Mode nickname became iconic during playoff run',
      'Had 5 receptions for 18 yards receiving',
      'Key part of balanced offensive attack',
    ],
  },
  // ============================================
  // 2025 SEAHAWKS DEFENSE
  // ============================================
  {
    id: '2025-devon-witherspoon',
    name: 'Devon Witherspoon',
    jersey_number: 21,
    position: 'Cornerback',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4429013.png',
    stats: { 'Solo Tackles': '54', 'Interceptions': '1', 'Pass Breakups': '4', 'Pressures': '10' },
    trivia: [
      '2025 Pro Bowl selection - consecutive Pro Bowls to start career',
      'Led all cornerbacks with 10 total pressures in 2025',
      'Played all 17 games - achieved full availability goal',
      'Fifth Seahawk to begin career with back-to-back Pro Bowls',
    ],
    bio: 'Seahawks CB - 2025 Pro Bowl',
    super_bowl_highlight: 'Shutdown corner for league-leading defense',
    display_order: 4,
    is_active: true,
  },
  {
    id: '2025-boye-mafe',
    name: 'Boye Mafe',
    jersey_number: 53,
    position: 'Outside Linebacker',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/4240754.png',
    stats: { 'Sacks': '6.0', 'Tackles': '30', 'TFL': '8', 'QB Hits': '12', 'Forced Fumbles': '1' },
    trivia: [
      '6.0 sacks in 2025 regular season',
      'Career total of 20.0 sacks through 2025',
      'Pro Bowl alternate in 2025',
      'Key pass rusher with sack, INT, and blocked kick in playoffs',
    ],
    bio: 'Seahawks OLB - Pass Rush Specialist',
    super_bowl_highlight: 'Playoff performer with big plays',
    display_order: 5,
    is_active: true,
  },
  {
    id: '2025-leonard-williams',
    name: 'Leonard Williams',
    jersey_number: 99,
    position: 'Defensive Lineman',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/2971622.png',
    stats: { 'Sacks': '7.0', 'Total Tackles': '62', 'QB Pressures': '40', 'TFL': '10' },
    trivia: [
      'NFC Defensive Player of the Month (Dec/Jan 2025)',
      'Top 10 among DTs in sacks, pressures, and pass rush win rate',
      '6 sacks in final month of regular season',
      'Sacked Brock Purdy in NFC Divisional Round',
    ],
    bio: 'Seahawks DL - NFC Defensive Player of Month',
    super_bowl_highlight: 'Dominant interior presence',
    display_order: 6,
    is_active: true,
  },
  {
    id: '2025-julian-love',
    name: 'Julian Love',
    jersey_number: 26,
    position: 'Safety',
    image_url: 'https://a.espncdn.com/i/headshots/nfl/players/full/3916148.png',
    stats: { 'Solo Tackles': '35', 'Forced Fumbles': '2', 'Pass Breakups': '4', 'Missed Tackle %': '7.8%' },
    trivia: [
      'Pro Bowl alternate - playing at All-Pro level in 2025',
      '4th among safeties in solo tackles (35)',
      'Versatile - plays safety, slot, and linebacker roles',
      'Key blitzer with sack on Brock Purdy in Week 1',
    ],
    bio: 'Seahawks S - Versatile Playmaker',
    super_bowl_highlight: 'Defensive QB of the secondary',
    display_order: 7,
    is_active: true,
  },
  // ============================================
  // SUPER BOWL XLVIII HEROES (2014)
  // ============================================
  {
    id: 'sbxlviii-russell-wilson',
    name: 'Russell Wilson',
    jersey_number: 3,
    position: 'Quarterback',
    image_url: null,
    stats: { 'SB Pass Yds': '206', 'SB Pass TD': '2', 'SB CMP/ATT': '18/25', 'SB Rating': '123.1' },
    trivia: [
      'Led Seahawks to 43-8 Super Bowl XLVIII victory',
      'Became 2nd Black QB to win a Super Bowl',
      'Led game-opening 80-yard TD drive in 12 plays',
      'At 25, one of youngest QBs to win championship',
    ],
    bio: 'Super Bowl XLVIII Champion QB',
    super_bowl_highlight: 'Led the Seahawks to a 43-8 victory in Super Bowl XLVIII',
    display_order: 10,
    is_active: false,
    imageUrl: 'https://images.unsplash.com/photo-1547992454-7f5625e65404?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMGNvcm5lcmJhY2slMjBkZWZlbnNpdmUlMjBwbGF5ZXJ8ZW58MXx8fHwxNzcwMTk4MTUzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'Tackles', value: '3' },
      { label: 'Pass Def', value: '2' },
      { label: 'INTs', value: '0' },
      { label: 'QB Hits', value: '0' },
    ],
    superBowlHighlight: 'Locked down receivers as part of the Legion of Boom.',
    trivia: [
      'Helped hold Peyton Manning to just 1 passing TD',
      'Part of secondary that forced 4 turnovers',
      'Legion of Boom dominated Denver receivers',
      'Stanford grad known for elite coverage skills',
    ],
  },
  {
    id: 'sbxlviii-marshawn-lynch',
    name: 'Marshawn Lynch',
    jersey_number: 24,
    position: 'Running Back',
    image_url: null,
    stats: { 'SB Rush Yds': '39', 'SB Rush TD': '1', 'SB Carries': '15', 'SB YPC': '2.6' },
    trivia: [
      'Scored Seahawks first Super Bowl TD in franchise history',
      'Iconic power runner nicknamed Beast Mode',
      'Famous Beast Quake run in 2011 playoffs',
      'Fan favorite known for loving Skittles',
    ],
    bio: 'Super Bowl XLVIII Champion RB - Beast Mode',
    super_bowl_highlight: 'Beast Mode touchdown run in Super Bowl XLVIII',
    display_order: 11,
    is_active: false,
  },
  {
    id: 'sbxlviii-malcolm-smith',
    name: 'Malcolm Smith',
    jersey_number: 53,
    position: 'Linebacker',
    image_url: null,
    stats: { 'SB Tackles': '10', 'SB INT': '1', 'SB INT Yds': '69', 'SB Fumble Rec': '1' },
    trivia: [
      'Named Super Bowl XLVIII MVP',
      'Returned interception 69 yards for touchdown',
      'Also recovered a fumble in the game',
      'Unsung hero who rose to biggest moment',
    ],
    bio: 'Super Bowl XLVIII MVP',
    super_bowl_highlight: 'Super Bowl XLVIII MVP with pick-six',
    display_order: 12,
    is_active: false,
    imageUrl: 'https://images.unsplash.com/photo-1547992454-1ee84f192799?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMGxpbmViYWNrZXIlMjBhY3Rpb258ZW58MXx8fHwxNzcwMTk4MTUzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'Tackles', value: '9' },
      { label: 'Interceptions', value: '1' },
      { label: 'Touchdowns', value: '1' },
      { label: 'Fumble Rec', value: '1' },
    ],
    superBowlHighlight: 'Super Bowl MVP with a pick-six and fumble recovery.',
    trivia: [
      'Won Super Bowl MVP as a little-known linebacker',
      'Returned interception 69 yards for a TD',
      'Recovered a Demaryius Thomas fumble',
      'First linebacker to win SB MVP since 2003',
    ],
  },
  {
    id: 'sbxlviii-richard-sherman',
    name: 'Richard Sherman',
    jersey_number: 25,
    position: 'Cornerback',
    image_url: null,
    stats: { 'SB Tackles': '3', 'SB Pass Deflections': '2', 'Pro Bowls': '5', 'All-Pro': '3x' },
    trivia: [
      'Made famous tip play to seal 2013 NFC Championship',
      '3-time First-Team All-Pro cornerback',
      'Stanford graduate with Communications degree',
      'Leader of the Legion of Boom secondary',
    ],
    bio: 'Legion of Boom - All-Pro Corner',
    super_bowl_highlight: 'Key interception sealing NFC Championship',
    display_order: 13,
    is_active: false,
  },
  {
    id: 'sbxlviii-earl-thomas',
    name: 'Earl Thomas',
    jersey_number: 29,
    position: 'Safety',
    image_url: null,
    stats: { 'SB Tackles': '5', 'SB Pass Deflections': '2', 'Pro Bowls': '7', 'All-Pro': '3x' },
    trivia: [
      '3-time First-Team All-Pro safety',
      'Fastest safety in the Legion of Boom',
      '7 Pro Bowl selections total',
      'Elite ball hawk and center fielder',
    ],
    bio: 'Legion of Boom - Elite Free Safety',
    super_bowl_highlight: 'Legion of Boom leader, 2 interceptions in playoffs',
    display_order: 14,
    is_active: false,
    number: 29,
    position: 'Free Safety',
    imageUrl: 'https://images.unsplash.com/photo-1761258772151-355fcec6d882?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMHBsYXllciUyMGRlZmVuc2UlMjBhdGhsZXRlfGVufDF8fHx8MTc3MDE5ODE1N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'Tackles', value: '5' },
      { label: 'Pass Def', value: '1' },
      { label: 'INTs', value: '0' },
      { label: 'Solo Tackles', value: '4' },
    ],
    superBowlHighlight: 'Patrolled the deep middle and disrupted Denver\'s passing game.',
    trivia: [
      'Centerfielder of the Legion of Boom defense',
      'Elite range disrupted Manning\'s deep passing',
      'First-team All-Pro selection that season',
      'Texas native drafted in 2010 first round',
    ],
  },
  {
    id: 'sbxlviii-kam-chancellor',
    name: 'Kam Chancellor',
    jersey_number: 31,
    position: 'Safety',
    image_url: null,
    stats: { 'SB Tackles': '7', 'SB Forced Fumbles': '1', 'SB Pass Deflections': '1', 'Pro Bowls': '4' },
    trivia: [
      'Known as Bam Bam Kam for devastating hits',
      '4-time Pro Bowl selection',
      'Key enforcer of Legion of Boom',
      'Forced crucial fumble in Super Bowl',
    ],
    bio: 'Legion of Boom - The Enforcer',
    super_bowl_highlight: 'Devastating hits and forced fumbles',
    display_order: 15,
    is_active: false,
    number: 31,
    position: 'Strong Safety',
    imageUrl: 'https://images.unsplash.com/photo-1547992454-1ee84f192799?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMHN0cm9uZyUyMHNhZmV0eSUyMHRhY2tsZXxlbnwxfHx8fDE3NzAxOTgxNTR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'Tackles', value: '7' },
      { label: 'Pass Def', value: '1' },
      { label: 'INTs', value: '0' },
      { label: 'Solo Tackles', value: '5' },
    ],
    superBowlHighlight: 'Delivered bone-crushing hits that intimidated Denver receivers.',
    trivia: [
      'Known as "Bam Bam" for his physical play',
      'Intimidated receivers across the middle',
      'Key enforcer in Legion of Boom secondary',
      'Virginia Tech product drafted in 2010',
    ],
  },
  // ============================================
  // HALL OF FAME LEGENDS
  // ============================================
  {
    id: 'hof-steve-largent',
    name: 'Steve Largent',
    jersey_number: 80,
    position: 'Wide Receiver',
    image_url: 'https://www.profootballhof.com/pfhof/media/Default/Items/Largent_Steve_HS_150.jpg',
    stats: { 'HOF Class': '1995', 'Career Rec': '819', 'Career Yds': '13,089', 'Career TD': '100' },
    trivia: [
      'First Seahawk inducted into Pro Football Hall of Fame',
      'Elected to HOF on January 28, 1995',
      'Held NFL records for receptions and yards at retirement',
      'Played entire 14-year career with Seattle',
    ],
    bio: 'Seahawks Legend - Hall of Fame (1995)',
    super_bowl_highlight: 'Franchise icon before Super Bowl era',
    display_order: 20,
    is_active: false,
  },
  {
    id: 'hof-walter-jones',
    name: 'Walter Jones',
    jersey_number: 71,
    position: 'Offensive Tackle',
    image_url: 'https://www.profootballhof.com/pfhof/media/Default/Items/Jones_Walter_HS-Capsule.jpg',
    stats: { 'HOF Class': '2014', 'Pro Bowls': '9', 'All-Pro': '4x First Team', 'Sacks Allowed': '23' },
    trivia: [
      'One of greatest left tackles in NFL history',
      'Hall of Fame Class of 2014',
      'Played entire 13-year career for Seattle',
      'Allowed only 23 sacks in entire career',
    ],
    bio: 'Seahawks Legend - Hall of Fame (2014)',
    super_bowl_highlight: 'Protected QBs for 13 seasons',
    display_order: 21,
    is_active: false,
  },
  {
    id: 'hof-cortez-kennedy',
    name: 'Cortez Kennedy',
    jersey_number: 96,
    position: 'Defensive Tackle',
    image_url: 'https://www.profootballhof.com/pfhof/media/Default/Items/Kennedy_Cortez_Action_Bio.jpg',
    stats: { 'HOF Class': '2012', 'Pro Bowls': '8', 'All-Pro': '3x', 'Sacks': '58' },
    trivia: [
      'Dominant Seahawks defensive tackle',
      'Hall of Fame Class of 2012',
      '8-time Pro Bowl selection',
      '1992 NFL Defensive Player of the Year',
    ],
    bio: 'Seahawks Legend - Hall of Fame (2012)',
    super_bowl_highlight: 'Franchise defensive star',
    display_order: 22,
    is_active: false,
    imageUrl: 'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMHdpZGUlMjByZWNlaXZlciUyMHNwcmludHxlbnwxfHx8fDE3NzAxOTgxNTR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'KR Yards', value: '87' },
      { label: 'KR TD', value: '1' },
      { label: 'Rec Yards', value: '45' },
      { label: 'Receptions', value: '1' },
    ],
    superBowlHighlight: 'Explosive 87-yard kickoff return TD to open the second half.',
    trivia: [
      'Returned second-half kickoff 87 yards for TD',
      'Fastest score to open a half in SB history',
      'Had battled injuries throughout the season',
      'Former Florida Gator and Vikings star',
    ],
  },
  {
    id: '8',
    name: 'Doug Baldwin',
    number: 89,
    position: 'Wide Receiver',
    imageUrl: 'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMHdpZGUlMjByZWNlaXZlciUyMGNhdGNofGVufDF8fHx8MTc3MDE5ODE1NHww&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'Receptions', value: '5' },
      { label: 'Yards', value: '66' },
      { label: 'Avg Yards', value: '13.2' },
      { label: 'Touchdowns', value: '0' },
    ],
    superBowlHighlight: 'Reliable target for Wilson throughout the game.',
    trivia: [
      'Undrafted free agent who became star WR',
      'Led team in receiving yards in the game',
      'Stanford connection with Richard Sherman',
      'Known as "Angry Doug" for competitive fire',
    ],
  },
  {
    id: 'hof-kenny-easley',
    name: 'Kenny Easley',
    jersey_number: 45,
    position: 'Safety',
    image_url: 'https://www.profootballhof.com/pfhof/media/Default/Items/Easley_Kenny_HS_150.jpg',
    stats: { 'HOF Class': '2017', 'Pro Bowls': '5', 'All-Pro': '3x', 'INT': '32' },
    trivia: [
      'Hall of Fame Class of 2017',
      '1984 NFL Defensive Player of the Year',
      'Played entire 7-year career in Seattle',
      'Elite range and impact plays in secondary',
    ],
    bio: 'Seahawks Legend - Hall of Fame (2017)',
    super_bowl_highlight: 'Pioneering Seahawks safety',
    display_order: 23,
    is_active: false,
  },
]

// Helper to get players by category
export const getCurrentPlayers = () => samplePlayers.filter(p => p.is_active)
export const getSuperBowlHeroes = () => samplePlayers.filter(p => p.id.startsWith('sbxlviii'))
export const getHallOfFamers = () => samplePlayers.filter(p => p.id.startsWith('hof'))

// Demo leaderboard
export const sampleLeaderboard = [
  { rank: 1, username: 'Legion of Boom', avatar: 'hawk' as AvatarId, total_points: 2450, current_streak: 5, days_played: 4 },
  { rank: 2, username: '12th Man Army', avatar: '12th_man' as AvatarId, total_points: 2100, current_streak: 3, days_played: 4 },
  { rank: 3, username: 'Beast Mode', avatar: 'champion' as AvatarId, total_points: 1850, current_streak: 2, days_played: 3 },
  { rank: 4, username: 'Sea Hawks Rising', avatar: 'fire' as AvatarId, total_points: 1600, current_streak: 4, days_played: 3 },
  { rank: 5, username: 'Blue Thunder', avatar: 'sparkle' as AvatarId, total_points: 1400, current_streak: 1, days_played: 2 },
]

// Demo photos for photo wall - incentivize sharing
export const samplePhotos = [
  {
    id: 'demo-0',
    teamId: 'demo-team-0',
    teamName: 'Lumen Field Crew',
    imageUrl: '/photos/seattle-skyline-hawks.svg',
    caption: 'Game day at Lumen Field! Go Hawks!',
    likes: 67,
    createdAt: '2024-02-03T19:30:00Z',
  },
  {
    id: 'demo-1',
    teamId: 'demo-team-1',
    teamName: 'Hawk Nation',
    imageUrl: '/photos/seahawks-mountain.svg',
    caption: 'The 12s are everywhere! Share your Seahawks pride!',
    likes: 42,
    createdAt: '2024-02-02T14:30:00Z',
  },
  {
    id: 'demo-2',
    teamId: 'demo-team-2',
    teamName: 'Legion of Boom',
    imageUrl: '/photos/blitz-mascot.svg',
    caption: 'Blitz says: Upload your game day photos!',
    likes: 38,
    createdAt: '2024-02-02T12:15:00Z',
  },
  {
    id: 'demo-3',
    teamId: 'demo-team-3',
    teamName: '12th Man Crew',
    imageUrl: '/photos/gameday-fans.svg',
    caption: 'Game day with the crew! Show us your 12 pride!',
    likes: 56,
    createdAt: '2024-02-01T18:45:00Z',
  },
  {
    id: 'demo-4',
    teamId: 'demo-team-4',
    teamName: 'Seattle Spirit',
    imageUrl: '/photos/seattle-skyline-hawks.svg',
    caption: 'Seattle skyline + Seahawks = perfection. Share your view!',
    likes: 31,
    createdAt: '2024-02-01T10:00:00Z',
  },
];
