import type { TriviaQuestion, Player, Score, Photo } from './types';

export const sampleQuestions: TriviaQuestion[] = [
  {
    id: '1',
    question: 'What year did the Seattle Seahawks win their first Super Bowl?',
    imageUrl: null,
    options: ['2012', '2013', '2014', '2015'],
    correctAnswer: 1,
    difficulty: 'easy',
    category: 'History',
    explanation: 'The Seahawks won Super Bowl XLVIII on February 2, 2014, defeating the Denver Broncos 43-8.'
  },
  {
    id: '2',
    question: 'Who was named Super Bowl XLVIII MVP?',
    imageUrl: null,
    options: ['Russell Wilson', 'Marshawn Lynch', 'Malcolm Smith', 'Richard Sherman'],
    correctAnswer: 2,
    difficulty: 'medium',
    category: 'Players',
    explanation: 'Linebacker Malcolm Smith was named MVP after recording an interception return for a touchdown and a fumble recovery.'
  },
  {
    id: '3',
    question: 'What was the final score of Super Bowl XLVIII?',
    imageUrl: null,
    options: ['43-8', '34-17', '28-24', '31-10'],
    correctAnswer: 0,
    difficulty: 'easy',
    category: 'History',
    explanation: 'The Seahawks dominated the Broncos 43-8, the largest margin of victory in Super Bowl history at the time.'
  },
  {
    id: '4',
    question: 'Who returned the opening kickoff of Super Bowl XLVIII for a touchdown?',
    imageUrl: null,
    options: ['Golden Tate', 'Percy Harvin', 'Doug Baldwin', 'Jermaine Kearse'],
    correctAnswer: 1,
    difficulty: 'hard',
    category: 'Plays',
    explanation: 'Percy Harvin returned the second-half kickoff 87 yards for a touchdown.'
  },
  {
    id: '5',
    question: 'What nickname was given to the Seahawks\' dominant defense?',
    imageUrl: null,
    options: ['Steel Curtain', 'Legion of Doom', 'Legion of Boom', 'Fearsome Foursome'],
    correctAnswer: 2,
    difficulty: 'easy',
    category: 'Trivia',
    explanation: 'The Legion of Boom featured stars like Richard Sherman, Earl Thomas, Kam Chancellor, and Bobby Wagner.'
  },
  {
    id: '6',
    question: 'How many touchdowns did Russell Wilson throw in Super Bowl XLVIII?',
    imageUrl: null,
    options: ['1', '2', '3', '4'],
    correctAnswer: 1,
    difficulty: 'medium',
    category: 'Stats',
    explanation: 'Russell Wilson threw 2 touchdown passes in the Super Bowl victory.'
  },
  {
    id: '7',
    question: 'Which team did the Seahawks defeat in the NFC Championship to reach Super Bowl XLVIII?',
    imageUrl: null,
    options: ['Green Bay Packers', 'San Francisco 49ers', 'New Orleans Saints', 'Carolina Panthers'],
    correctAnswer: 1,
    difficulty: 'medium',
    category: 'History',
    explanation: 'The Seahawks defeated the 49ers 23-17 in the NFC Championship Game.'
  },
  {
    id: '8',
    question: 'What was the halftime score of Super Bowl XLVIII?',
    imageUrl: null,
    options: ['15-0', '22-0', '29-0', '36-0'],
    correctAnswer: 1,
    difficulty: 'hard',
    category: 'History',
    explanation: 'The Seahawks led 22-0 at halftime, completely dominating the Broncos.'
  },
  {
    id: '9',
    question: 'Who caught a 23-yard touchdown pass from Russell Wilson in Super Bowl XLVIII?',
    imageUrl: null,
    options: ['Golden Tate', 'Doug Baldwin', 'Jermaine Kearse', 'Luke Willson'],
    correctAnswer: 2,
    difficulty: 'hard',
    category: 'Plays',
    explanation: 'Jermaine Kearse caught a 23-yard touchdown pass in the fourth quarter.'
  },
  {
    id: '10',
    question: 'In what stadium was Super Bowl XLVIII played?',
    imageUrl: null,
    options: ['University of Phoenix Stadium', 'MetLife Stadium', 'Levi\'s Stadium', 'Mercedes-Benz Stadium'],
    correctAnswer: 1,
    difficulty: 'medium',
    category: 'Trivia',
    explanation: 'Super Bowl XLVIII was played at MetLife Stadium in East Rutherford, New Jersey.'
  },
];

export const samplePlayers: Player[] = [
  {
    id: '1',
    name: 'Russell Wilson',
    number: 3,
    position: 'Quarterback',
    imageUrl: 'https://images.unsplash.com/photo-1761258772149-c0ba7e8db954?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhbWVyaWNhbiUyMGZvb3RiYWxsJTIwcXVhcnRlcmJhY2slMjBhY3Rpb258ZW58MXx8fHwxNzcwMTk4MTUyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'Passing Yards', value: '206' },
      { label: 'Touchdowns', value: '2' },
      { label: 'Completion %', value: '72.4%' },
      { label: 'QBR', value: '123.1' },
    ],
    superBowlHighlight: 'Led the offense with precision passing and two touchdown throws.',
    trivia: [
      'Became the 2nd Black QB to win a Super Bowl',
      'Led game-opening 80-yard TD drive in 12 plays',
      'Threw TD passes to Jermaine Kearse and Doug Baldwin',
      'At 25, one of the youngest QBs to win a championship',
    ],
  },
  {
    id: '2',
    name: 'Marshawn Lynch',
    number: 24,
    position: 'Running Back',
    imageUrl: 'https://images.unsplash.com/photo-1593051531088-fd52df065aa2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMHJ1bm5pbmclMjBiYWNrJTIwYXRobGV0ZXxlbnwxfHx8fDE3NzAxOTgxNTJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'Rush Yards', value: '39' },
      { label: 'Touchdowns', value: '1' },
      { label: 'Carries', value: '15' },
      { label: 'Avg Yards', value: '2.6' },
    ],
    superBowlHighlight: 'Beast Mode powered through for a crucial touchdown run.',
    trivia: [
      'Scored on a 1-yard TD run in the 3rd quarter',
      'Beast Mode nickname became iconic during playoff run',
      'Had 5 receptions for 18 yards receiving',
      'Key part of balanced offensive attack',
    ],
  },
  {
    id: '3',
    name: 'Richard Sherman',
    number: 25,
    position: 'Cornerback',
    imageUrl: 'https://images.unsplash.com/photo-1547992454-7f5625e65404?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMGNvcm5lcmJhY2slMjBkZWZlbnNpdmUlMjBwbGF5ZXJ8ZW58MXx8fHwxNzcwMTk4MTUzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'Tackles', value: '3' },
      { label: 'Pass Def', value: '2' },
      { label: 'INTs', value: '0' },
      { label: 'QB Hits', value: '0' },
    ],
    superBowlHighlight: 'Locked down receivers as part of the Legion of Boom.',
    trivia: [
      'Helped hold Peyton Manning to just 1 passing TD',
      'Part of secondary that forced 4 turnovers',
      'Legion of Boom dominated Denver receivers',
      'Stanford grad known for elite coverage skills',
    ],
  },
  {
    id: '4',
    name: 'Malcolm Smith',
    number: 53,
    position: 'Linebacker',
    imageUrl: 'https://images.unsplash.com/photo-1547992454-1ee84f192799?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMGxpbmViYWNrZXIlMjBhY3Rpb258ZW58MXx8fHwxNzcwMTk4MTUzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'Tackles', value: '9' },
      { label: 'Interceptions', value: '1' },
      { label: 'Touchdowns', value: '1' },
      { label: 'Fumble Rec', value: '1' },
    ],
    superBowlHighlight: 'Super Bowl MVP with a pick-six and fumble recovery.',
    trivia: [
      'Won Super Bowl MVP as a little-known linebacker',
      'Returned interception 69 yards for a TD',
      'Recovered a Demaryius Thomas fumble',
      'First linebacker to win SB MVP since 2003',
    ],
  },
  {
    id: '5',
    name: 'Earl Thomas',
    number: 29,
    position: 'Free Safety',
    imageUrl: 'https://images.unsplash.com/photo-1761258772151-355fcec6d882?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMHBsYXllciUyMGRlZmVuc2UlMjBhdGhsZXRlfGVufDF8fHx8MTc3MDE5ODE1N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'Tackles', value: '5' },
      { label: 'Pass Def', value: '1' },
      { label: 'INTs', value: '0' },
      { label: 'Solo Tackles', value: '4' },
    ],
    superBowlHighlight: 'Patrolled the deep middle and disrupted Denver\'s passing game.',
    trivia: [
      'Centerfielder of the Legion of Boom defense',
      'Elite range disrupted Manning\'s deep passing',
      'First-team All-Pro selection that season',
      'Texas native drafted in 2010 first round',
    ],
  },
  {
    id: '6',
    name: 'Kam Chancellor',
    number: 31,
    position: 'Strong Safety',
    imageUrl: 'https://images.unsplash.com/photo-1547992454-1ee84f192799?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMHN0cm9uZyUyMHNhZmV0eSUyMHRhY2tsZXxlbnwxfHx8fDE3NzAxOTgxNTR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'Tackles', value: '7' },
      { label: 'Pass Def', value: '1' },
      { label: 'INTs', value: '0' },
      { label: 'Solo Tackles', value: '5' },
    ],
    superBowlHighlight: 'Delivered bone-crushing hits that intimidated Denver receivers.',
    trivia: [
      'Known as "Bam Bam" for his physical play',
      'Intimidated receivers across the middle',
      'Key enforcer in Legion of Boom secondary',
      'Virginia Tech product drafted in 2010',
    ],
  },
  {
    id: '7',
    name: 'Percy Harvin',
    number: 11,
    position: 'Wide Receiver',
    imageUrl: 'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMHdpZGUlMjByZWNlaXZlciUyMHNwcmludHxlbnwxfHx8fDE3NzAxOTgxNTR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'KR Yards', value: '87' },
      { label: 'KR TD', value: '1' },
      { label: 'Rec Yards', value: '45' },
      { label: 'Receptions', value: '1' },
    ],
    superBowlHighlight: 'Explosive 87-yard kickoff return TD to open the second half.',
    trivia: [
      'Returned second-half kickoff 87 yards for TD',
      'Fastest score to open a half in SB history',
      'Had battled injuries throughout the season',
      'Former Florida Gator and Vikings star',
    ],
  },
  {
    id: '8',
    name: 'Doug Baldwin',
    number: 89,
    position: 'Wide Receiver',
    imageUrl: 'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMHdpZGUlMjByZWNlaXZlciUyMGNhdGNofGVufDF8fHx8MTc3MDE5ODE1NHww&ixlib=rb-4.1.0&q=80&w=1080',
    stats: [
      { label: 'Receptions', value: '5' },
      { label: 'Yards', value: '66' },
      { label: 'Avg Yards', value: '13.2' },
      { label: 'Touchdowns', value: '0' },
    ],
    superBowlHighlight: 'Reliable target for Wilson throughout the game.',
    trivia: [
      'Undrafted free agent who became star WR',
      'Led team in receiving yards in the game',
      'Stanford connection with Richard Sherman',
      'Known as "Angry Doug" for competitive fire',
    ],
  },
];

export const sampleScores: Score[] = [
  {
    id: '1',
    teamId: 't1',
    teamName: 'The 12th Men',
    teamImage: null,
    points: 450,
    correctAnswers: 45,
    totalAnswers: 50,
    streak: 5,
    lastPlayedDate: '2024-02-01',
  },
  {
    id: '2',
    teamId: 't2',
    teamName: 'Legion of Trivia',
    teamImage: null,
    points: 420,
    correctAnswers: 42,
    totalAnswers: 50,
    streak: 3,
    lastPlayedDate: '2024-02-01',
  },
  {
    id: '3',
    teamId: 't3',
    teamName: 'Beast Mode Quiz',
    teamImage: null,
    points: 380,
    correctAnswers: 38,
    totalAnswers: 50,
    streak: 2,
    lastPlayedDate: '2024-02-01',
  },
  {
    id: '4',
    teamId: 't4',
    teamName: 'Blue Thunder',
    teamImage: null,
    points: 350,
    correctAnswers: 35,
    totalAnswers: 50,
    streak: 0,
    lastPlayedDate: '2024-01-31',
  },
  {
    id: '5',
    teamId: 't5',
    teamName: 'Hawk Nation',
    teamImage: null,
    points: 320,
    correctAnswers: 32,
    totalAnswers: 50,
    streak: 1,
    lastPlayedDate: '2024-02-01',
  },
];

export const samplePhotos: Photo[] = [
  {
    id: '1',
    teamId: 't1',
    teamName: 'The 12th Men',
    imageUrl: '/photos/sample1.jpg',
    caption: 'Game day ready! Go Hawks!',
    likes: 24,
    createdAt: '2024-02-01T14:30:00Z',
  },
  {
    id: '2',
    teamId: 't2',
    teamName: 'Legion of Trivia',
    imageUrl: '/photos/sample2.jpg',
    caption: 'Throwback to Super Bowl XLVIII',
    likes: 18,
    createdAt: '2024-02-01T12:15:00Z',
  },
  {
    id: '3',
    teamId: 't3',
    teamName: 'Beast Mode Quiz',
    imageUrl: '/photos/sample3.jpg',
    caption: 'Beast Mode activated!',
    likes: 31,
    createdAt: '2024-01-31T18:45:00Z',
  },
];

export const teamAvatars = [
  { id: 'hawk', name: 'Hawk', emoji: '🦅' },
  { id: 'blitz', name: 'Blitz', emoji: '🦅💚' },
  { id: '12', name: '#12', emoji: '1️⃣2️⃣' },
  { id: 'superfan', name: 'Superfan', emoji: '🙋🏽‍♀️' },
  { id: '12thman', name: '12th Man', emoji: '🙋🏻‍♂️' },
  { id: 'girlsrule', name: 'Girls Rule', emoji: '👸' },
  { id: 'hero', name: 'Hero', emoji: '🧝‍♂️' },
  { id: 'champion', name: 'Champion', emoji: '👨🏾‍🦲' },
  { id: 'trophy', name: 'Trophy', emoji: '🏆' },
  { id: 'queen', name: 'Queen', emoji: '👑' },
  { id: 'sparkle', name: 'Sparkle', emoji: '✨' },
  { id: 'fire', name: 'Fire', emoji: '🔥' },
];

export const suggestedTeamNames = [
  'Legion of Boom',
  '12th Man Legends',
  'Sea Hawks Rising',
  'Blue Thunder',
  'Beast Mode',
];
