import { AVATARS, type AvatarId } from './database.types'

// Re-export avatars for components
export const teamAvatars = Object.values(AVATARS).map(avatar => ({
  id: avatar.id as AvatarId,
  name: avatar.name,
  emoji: avatar.emoji,
}))

// Suggested team names for quick selection
export const suggestedTeamNames = [
  'Legion of Boom',
  '12th Man Legends',
  'Sea Hawks Rising',
  'Beast Mode',
  'Blue Thunder',
  'Hawk Nation',
  'The 12s',
  'Super Bowl Champs',
]

// Available question categories for daily rounds
export const questionCategories = [
  'Super Bowl XLVIII',
  'Legion of Boom',
  'Russell Wilson Era',
  'Seahawks Legends',
  'Stadium & 12s',
  'Memorable Moments',
  'Players & Numbers',
  'Seahawks History',
]

// Demo questions (used when Supabase not configured)
// Organized by category for easy filtering
export const sampleQuestions = [
  // Super Bowl XLVIII
  {
    id: 'demo-1',
    question_text: 'What year did the Seattle Seahawks win their first Super Bowl?',
    option_a: '2012',
    option_b: '2013',
    option_c: '2014',
    option_d: '2015',
    correct_answer: 'b' as const,
    hint_text: 'The season was 2013-2014',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Super Bowl XLVIII',
  },
  {
    id: 'demo-2',
    question_text: 'Who was named MVP of Super Bowl XLVIII?',
    option_a: 'Russell Wilson',
    option_b: 'Marshawn Lynch',
    option_c: 'Malcolm Smith',
    option_d: 'Richard Sherman',
    correct_answer: 'c' as const,
    hint_text: 'He had a pick-six',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Super Bowl XLVIII',
  },
  {
    id: 'demo-3',
    question_text: 'What was the final score of Super Bowl XLVIII?',
    option_a: '43-8',
    option_b: '34-7',
    option_c: '38-10',
    option_d: '41-14',
    correct_answer: 'a' as const,
    hint_text: 'It was the largest margin in Super Bowl history at the time',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Super Bowl XLVIII',
  },
  {
    id: 'demo-4',
    question_text: 'Which team did the Seahawks defeat in Super Bowl XLVIII?',
    option_a: 'New England Patriots',
    option_b: 'San Francisco 49ers',
    option_c: 'Denver Broncos',
    option_d: 'Green Bay Packers',
    correct_answer: 'c' as const,
    hint_text: 'They had the #1 offense that year',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Super Bowl XLVIII',
  },
  {
    id: 'demo-5',
    question_text: 'Who returned an interception for a touchdown in Super Bowl XLVIII?',
    option_a: 'Richard Sherman',
    option_b: 'Earl Thomas',
    option_c: 'Malcolm Smith',
    option_d: 'Kam Chancellor',
    correct_answer: 'c' as const,
    hint_text: 'He was also the MVP',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Super Bowl XLVIII',
  },
  // Legion of Boom
  {
    id: 'demo-6',
    question_text: 'What was the nickname of the Seahawks legendary defense?',
    option_a: 'Steel Curtain',
    option_b: 'Legion of Boom',
    option_c: 'Purple People Eaters',
    option_d: 'Monsters of the Midway',
    correct_answer: 'b' as const,
    hint_text: 'It references their big hits',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Legion of Boom',
  },
  {
    id: 'demo-7',
    question_text: 'Which three players formed the core of the Legion of Boom secondary?',
    option_a: 'Sherman, Thomas, Chancellor',
    option_b: 'Sherman, Thomas, Maxwell',
    option_c: 'Chancellor, Browner, Thomas',
    option_d: 'Sherman, Chancellor, Lane',
    correct_answer: 'a' as const,
    hint_text: 'Two safeties and a cornerback',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Legion of Boom',
  },
  {
    id: 'demo-8',
    question_text: 'What position did Richard Sherman play?',
    option_a: 'Free Safety',
    option_b: 'Strong Safety',
    option_c: 'Cornerback',
    option_d: 'Linebacker',
    correct_answer: 'c' as const,
    hint_text: 'He covered receivers on the outside',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Legion of Boom',
  },
  {
    id: 'demo-9',
    question_text: 'What jersey number did Earl Thomas wear?',
    option_a: '25',
    option_b: '29',
    option_c: '31',
    option_d: '33',
    correct_answer: 'b' as const,
    hint_text: 'It is an odd number',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Legion of Boom',
  },
  {
    id: 'demo-10',
    question_text: 'Which Legion of Boom member was known for devastating hits at the line of scrimmage?',
    option_a: 'Earl Thomas',
    option_b: 'Richard Sherman',
    option_c: 'Kam Chancellor',
    option_d: 'Brandon Browner',
    correct_answer: 'c' as const,
    hint_text: 'He played strong safety',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Legion of Boom',
  },
  // Memorable Moments
  {
    id: 'demo-11',
    question_text: 'Which Seahawk had the famous "tip" play in the 2013 NFC Championship?',
    option_a: 'Earl Thomas',
    option_b: 'Richard Sherman',
    option_c: 'Kam Chancellor',
    option_d: 'Byron Maxwell',
    correct_answer: 'b' as const,
    hint_text: 'He tipped it to a teammate for the interception',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Memorable Moments',
  },
  {
    id: 'demo-12',
    question_text: 'What was the famous Marshawn Lynch run in the 2010 playoffs called?',
    option_a: 'The Run',
    option_b: 'Beast Quake',
    option_c: 'Thunder Run',
    option_d: 'Lynch Mob',
    correct_answer: 'b' as const,
    hint_text: 'Fans caused a seismic event',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Memorable Moments',
  },
  {
    id: 'demo-13',
    question_text: 'Against which team did the "Beast Quake" run occur?',
    option_a: 'Green Bay Packers',
    option_b: 'New Orleans Saints',
    option_c: 'Dallas Cowboys',
    option_d: 'Atlanta Falcons',
    correct_answer: 'b' as const,
    hint_text: 'They were the defending Super Bowl champions',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Memorable Moments',
  },
  // Players & Numbers
  {
    id: 'demo-14',
    question_text: 'What jersey number did Beast Mode Marshawn Lynch wear?',
    option_a: '20',
    option_b: '22',
    option_c: '24',
    option_d: '28',
    correct_answer: 'c' as const,
    hint_text: 'It is an even number in the 20s',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Players & Numbers',
  },
  {
    id: 'demo-15',
    question_text: 'What jersey number did Russell Wilson wear with the Seahawks?',
    option_a: '1',
    option_b: '3',
    option_c: '7',
    option_d: '12',
    correct_answer: 'b' as const,
    hint_text: 'A single digit number',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Players & Numbers',
  },
  // Seahawks History
  {
    id: 'demo-16',
    question_text: 'What year were the Seattle Seahawks founded?',
    option_a: '1974',
    option_b: '1976',
    option_c: '1978',
    option_d: '1980',
    correct_answer: 'b' as const,
    hint_text: 'During Americas bicentennial',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Seahawks History',
  },
  {
    id: 'demo-17',
    question_text: 'What division are the Seahawks currently in?',
    option_a: 'NFC West',
    option_b: 'NFC North',
    option_c: 'AFC West',
    option_d: 'NFC South',
    correct_answer: 'a' as const,
    hint_text: 'They share it with the 49ers',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'easy' as const,
    category: 'Seahawks History',
  },
  {
    id: 'demo-18',
    question_text: 'How many times have the Seahawks appeared in the Super Bowl?',
    option_a: '1',
    option_b: '2',
    option_c: '3',
    option_d: '4',
    correct_answer: 'c' as const,
    hint_text: 'They won one of them',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Seahawks History',
  },
  // Seahawks Legends
  {
    id: 'demo-19',
    question_text: 'Who is the Seahawks all-time leading rusher?',
    option_a: 'Marshawn Lynch',
    option_b: 'Shaun Alexander',
    option_c: 'Chris Warren',
    option_d: 'Curt Warner',
    correct_answer: 'b' as const,
    hint_text: 'He won NFL MVP in 2005',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Seahawks Legends',
  },
  {
    id: 'demo-20',
    question_text: 'Which Seahawk won NFL MVP in 2005?',
    option_a: 'Matt Hasselbeck',
    option_b: 'Shaun Alexander',
    option_c: 'Walter Jones',
    option_d: 'Steve Largent',
    correct_answer: 'b' as const,
    hint_text: 'He was a running back',
    time_limit_seconds: 15,
    points: 100,
    difficulty: 'medium' as const,
    category: 'Seahawks Legends',
  },
]

// Helper to get questions by category
export const getQuestionsByCategory = (category: string) =>
  sampleQuestions.filter(q => q.category === category)

// Demo players with full baseball card data
export const samplePlayers = [
  {
    id: 'demo-1',
    name: 'Russell Wilson',
    jersey_number: 3,
    position: 'Quarterback',
    image_url: null,
    stats: { 'Passing Yards': '206', 'Touchdowns': '2', 'Completion %': '72.4%', 'QBR': '123.1' },
    trivia: [
      'Became the 2nd Black QB to win a Super Bowl',
      'Led game-opening 80-yard TD drive in 12 plays',
      'Threw TD passes to Jermaine Kearse and Doug Baldwin',
      'At 25, one of the youngest QBs to win a championship',
    ],
    bio: 'Super Bowl XLVIII Champion QB',
    super_bowl_highlight: 'Led the Seahawks to a 43-8 victory in Super Bowl XLVIII',
    display_order: 1,
    is_active: true,
  },
  {
    id: 'demo-2',
    name: 'Marshawn Lynch',
    jersey_number: 24,
    position: 'Running Back',
    image_url: null,
    stats: { 'Rushing Yards': '39', 'Touchdowns': '1', 'Receptions': '2', 'Total Yards': '52' },
    trivia: [
      'Scored on a powerful 1-yard TD run in the 3rd quarter',
      'Known as Beast Mode for his punishing running style',
      'Had the iconic Beast Quake run in 2011 playoffs',
      'Fan favorite who loved Skittles',
    ],
    bio: 'Beast Mode - Super Bowl Champion',
    super_bowl_highlight: 'Beast Mode touchdown run in Super Bowl XLVIII',
    display_order: 2,
    is_active: true,
  },
  {
    id: 'demo-3',
    name: 'Richard Sherman',
    jersey_number: 25,
    position: 'Cornerback',
    image_url: null,
    stats: { 'Tackles': '3', 'Pass Deflections': '2', 'Interceptions': '0', 'QB Rating Allowed': '52.1' },
    trivia: [
      'Made the famous tip play to seal 2013 NFC Championship',
      '3-time First-Team All-Pro cornerback',
      'Stanford graduate with degree in Communications',
      'Led the Legion of Boom secondary',
    ],
    bio: 'Legion of Boom - All-Pro Corner',
    super_bowl_highlight: 'Key interception sealing NFC Championship',
    display_order: 3,
    is_active: true,
  },
  {
    id: 'demo-4',
    name: 'Malcolm Smith',
    jersey_number: 53,
    position: 'Linebacker',
    image_url: null,
    stats: { 'Tackles': '10', 'Interceptions': '1', 'INT Return Yards': '69', 'Fumble Recovery': '1' },
    trivia: [
      'Named Super Bowl XLVIII MVP',
      'Returned an interception 69 yards for a touchdown',
      'Also recovered a fumble in the game',
      'Unsung hero who rose to the biggest moment',
    ],
    bio: 'Super Bowl XLVIII MVP',
    super_bowl_highlight: 'Super Bowl XLVIII MVP with pick-six',
    display_order: 4,
    is_active: true,
  },
  {
    id: 'demo-5',
    name: 'Earl Thomas',
    jersey_number: 29,
    position: 'Safety',
    image_url: null,
    stats: { 'Tackles': '5', 'Interceptions': '0', 'Pass Deflections': '2', 'QB Hits': '1' },
    trivia: [
      '3-time First-Team All-Pro safety',
      'Fastest safety in the Legion of Boom',
      '5 Pro Bowl selections with Seattle',
      'Elite ball hawk and center fielder',
    ],
    bio: 'Legion of Boom - Elite Free Safety',
    super_bowl_highlight: 'Legion of Boom leader, 2 interceptions in playoffs',
    display_order: 5,
    is_active: true,
  },
  {
    id: 'demo-6',
    name: 'Kam Chancellor',
    jersey_number: 31,
    position: 'Safety',
    image_url: null,
    stats: { 'Tackles': '7', 'Forced Fumbles': '1', 'Pass Deflections': '1', 'TFL': '1' },
    trivia: [
      'Known as Bam Bam Kam for devastating hits',
      '4-time Pro Bowl selection',
      'Key enforcer of the Legion of Boom',
      'Forced crucial fumble in Super Bowl',
    ],
    bio: 'Legion of Boom - The Enforcer',
    super_bowl_highlight: 'Devastating hits and forced fumbles',
    display_order: 6,
    is_active: true,
  },
]

// Demo leaderboard
export const sampleLeaderboard = [
  { rank: 1, username: 'Legion of Boom', avatar: 'hawk' as AvatarId, total_points: 2450, current_streak: 5, days_played: 4 },
  { rank: 2, username: '12th Man Army', avatar: '12th_man' as AvatarId, total_points: 2100, current_streak: 3, days_played: 4 },
  { rank: 3, username: 'Beast Mode', avatar: 'champion' as AvatarId, total_points: 1850, current_streak: 2, days_played: 3 },
  { rank: 4, username: 'Sea Hawks Rising', avatar: 'fire' as AvatarId, total_points: 1600, current_streak: 4, days_played: 3 },
  { rank: 5, username: 'Blue Thunder', avatar: 'sparkle' as AvatarId, total_points: 1400, current_streak: 1, days_played: 2 },
]

// Demo photos
export const samplePhotos = [
  {
    id: 'demo-1',
    username: 'Legion of Boom',
    user_avatar: 'hawk' as AvatarId,
    image_url: '/photos/sample1.jpg',
    caption: 'Game day ready! Go Hawks!',
    like_count: 24,
    created_at: '2024-02-01T14:30:00Z',
  },
  {
    id: 'demo-2',
    username: '12th Man Army',
    user_avatar: '12th_man' as AvatarId,
    image_url: '/photos/sample2.jpg',
    caption: 'Throwback to Super Bowl XLVIII',
    like_count: 18,
    created_at: '2024-02-01T12:15:00Z',
  },
  {
    id: 'demo-3',
    username: 'Beast Mode',
    user_avatar: 'champion' as AvatarId,
    image_url: '/photos/sample3.jpg',
    caption: 'Beast Mode activated!',
    like_count: 31,
    created_at: '2024-01-31T18:45:00Z',
  },
]
