// Matched by player name on the official active-roster pages, September 7, 2026.
// https://www.seahawks.com/team/players-roster/
// https://www.patriots.com/team/players-roster/
const HEADSHOTS: Record<string, Record<string, string>> = {
  '2026-hawks': {
    'Elijah Arroyo': 's5la50etcs7wwbcgiix6.jpg',
    'AJ Barner': 'fangcx1teg8zgacs6ydk.jpg',
    'Anthony Bradford': 'amr1ozjrwzaaztu6iqpj.jpg',
    'Bryce Cabeldue': 'mqkcrauekr84uf6srofh.jpg',
    'Charles Cross': 'kqcmrguuqfcb302ejfeg.jpg',
    'Sam Darnold': 'k9eisiyvr0az1qug6qy4.jpg',
    'Michael Dickson': 'rmqnrd0vt2z8sggsihzt.jpg',
    'Nick Emmanwori': 'mymazg0bndwgm1r71fjq.jpg',
    'Montorie Foster Jr': 'vihj7auozbxj8q1mvhnt.jpg',
    'Dante Fowler Jr.': 'b28dad7haz1gnov40eye.jpg',
    'Derick Hall': 'c8slto8doegjtnatvaxv.jpg',
    'Christian Haynes': 'fjrkdfskc14yjaabrtrr.jpg',
    'George Holani': 's3rrdv5gcimmfiqjfcur.jpg',
    'Tory Horton': 'zgntubgnmv5jmbbvyybj.jpg',
    'Josh Jobe': 'an5y1jefrncq498dn9wj.jpg',
    'Ernest Jones IV': 'bha8atcs8n3ns9vmwllg.jpg',
    'Josh Jones': 'r20h35s4ikrkgvqmrclr.jpg',
    'Nick Kallerup': 'pzewhkbtc3c6uayll13b.jpg',
    'Tyrice Knight': 'ys0shgiomb0rodyweoxx.jpg',
    'Cooper Kupp': 'gzxf4vg2ksrdkhp8k7uy.jpg',
    'DeMarcus Lawrence': 'zmia6vbyink6et3behfk.jpg',
    'Drew Lock': 'x6ykex1q21oal0uli9lv.jpg',
    'Julian Love': 'tsrncbiw6ewmpn0bzwja.jpg',
    'Abraham Lucas': 'b2wdm90pcl3w0fqha7kz.jpg',
    'Rylie Mills': 'idmkylczc0kmaubmqnqb.jpg',
    'Jalen Milroe': 'oalatyzhka6srzdyyqum.jpg',
    'Mike Morris': 'socfeiiwyjnymmibffib.jpg',
    'Byron Murphy II': 'fhxq1gzgt8qdbzydyx6m.jpg',
    'Jason Myers': 'bfeubxtqntkrnzqlwyli.jpg',
    'Julian Neal': 'w6ycbhdd76lfsb02cnfz.jpg',
    'Uchenna Nwosu': 'mxkgsfsx5nzj9uoazlnz.jpg',
    "Patrick O'Connell": 'vsvtlkcsld4dvih9a05d.jpg',
    'Ty Okada': 'tyc0ioiz06lf0nqteu08.jpg',
    'Olu Oluwatimi': 'trloccdlu9apbf2eyzcy.jpg',
    "Connor O'Toole": 'ozzyh58bmob2zfrgorx5.jpg',
    'Brandon Pili': 'mliz4ucncgulfgizd15r.jpg',
    'Jadarian Price': 'g6kx4aagsvzvokrz5fyv.jpg',
    'Nehemiah Pritchett': 'chrx7n4b901d6tj0sufr.jpg',
    'Jarran Reed': 'vfedlkre9tekn5yhyp3u.jpg',
    'Brady Russell': 'qnh6sthfnpwjlzukth4i.jpg',
    'Eric Saubert': 'jcxnkdgejmovajx8qou8.jpg',
    'Rashid Shaheed': 'svbut9yiy34rynbccf5z.jpg',
    'Avery Smith': 'l6ts0wguegjgxr67xm5n.jpg',
    'Jaxon Smith-Njigba': 'tp3wjscoyvqlgdb0vrsf.jpg',
    'Beau Stephens': 'lsxztw7h4ov6za7ftikq.jpg',
    'Chris Stoll': 'zgltykcsawpe0ptniiqb.jpg',
    'Jalen Sundell': 'eqongw9yuzhtpcfe6ggd.jpg',
    'Chazz Surratt': 'cny6x72vqyetjqvkdqvj.jpg',
    'Drake Thomas': 'ki98hlpvt02ly3eej9ne.jpg',
    'Leonard Williams': 'q1td1aqfgwujviknoaio.jpg',
    'Emanuel Wilson': 'oolw8ujjvi6rdw1qzme9.jpg',
    'Devon Witherspoon': 'heo6oul8g5vplxtkoduz.jpg',
    'Grey Zabel': 'sji6lbi0bchqaw2kj7ja.jpg',
  },
  '2026-pats': {
    'Tanner Arkin': 'ohjfuoiuc11fceehv15k.png',
    'Julian Ashby': 'ajajm4kpptgabflalkss.png',
    'Christian Barmore': 'xlselcvs4xreirvtt1fr.png',
    'Andy Borregales': 'uj43vmspvl2gbyl2gekf.png',
    'A.J. Brown': 'hxq9tprk9t5t3kzydrfj.png',
    'Ben Brown': 'f4h1vuzyhcfjg5wjscq4.png',
    'Kevin Byard III': 'zh1hmlx4o8xfnaz3rwv8.png',
    'Will Campbell': 'huydot1r2icviq5zqzca.png',
    'Channing Canada': 'yr5yiaxhaefolhy21tev.png',
    'Efton Chism III': 'ntbwjpuaut8vmo4qjfxp.png',
    'Dametrious Crownover': 'rn95o7ks2pyklbxwoo6m.png',
    'Carlton Davis III': 'mezuzabkdldmqea9ukos.png',
    'Tommy DeVito': 'roif5mllfysdfexludcu.png',
    'Romeo Doubs': 'wiiu7bejxw5rzrsucnqn.png',
    'DeMario Douglas': 'xk7njm9aooanll1xql8r.png',
    'Cory Durden': 'qwhbajntfzfpeaq0mkkx.png',
    'Christian Elliss': 'hi5zbq2gmpqqcqpqv3ak.png',
    'Joshua Farmer': 'o1vak6ujs3ttlkwxnbu4.png',
    'Reggie Gilliam': 'hkpbranrcfmic8ftk3xu.png',
    'Christian Gonzalez': 'q1bxrzqzjxyzyjjcicrf.png',
    'TreVeyon Henderson': 'zcd8n1ht411qmfzildd0.png',
    'Hunter Henry': 'puuawvfwh1rt4ork8fwh.png',
    'Mack Hollins': 'cwe4r4nd5w4uw4dwat4a.png',
    'Erick Hunter': 'vxtosij8muzvfhx37iso.png',
    'Quintayvious Hutchins': 's8cehd432ds8pkpbsx6z.png',
    'Gabe Jacas': 'zmol0z7e1un1e9ir5min.png',
    "Dre'Mont Jones": 'tbjz692maebzewtsrfmk.png',
    'Marcus Jones': 'ocrejgmtzanagzb3s8a3.png',
    'Corey Kiner': 'fbfmv4dpj5zzkqkryo6r.jpg',
    'Cameron Latu': 'zcznqkdz43xk8ryfryo3.jpg',
    'Caleb Lomu': 'byavnb7wt1n1mfchecte.png',
    'Drake Maye': 'yjmlljttlbzjwfiip1kc.png',
    'Behren Morton': 'jtnscd1utayexzbf0e08.png',
    'Morgan Moses': 'kzmqhxnpyyv3cwlghjgd.png',
    'Darius Muasau': 'o4l5mbzwcnqbh2wuhypr.jpg',
    'Namdi Obiazor': 'cipvdafulpyh7xgiu1xh.png',
    'Mike Onwenu': 'zlm8tlkqcy38tlnkbqz5.png',
    'Dell Pettus': 'he8avzevznfuhu0bue3c.png',
    'Elijah Ponder': 'kfjyl9dzpz8kufdxkr03.png',
    'Karon Prunty': 'aj7p92o7ite2fnyunyix.png',
    'Eli Raridon': 'yalycdft2ck03t5lva9p.png',
    'Jaylen Reed': 'c8z1csqispfhgwnzzudh.png',
    'Walter Rouse': 'purnlljtjxgnsgjghwbx.png',
    'Robert Spillane': 'nraoi2exztq8f5vj4yfq.png',
    'Rhamondre Stevenson': 'wlgpoebuzo7zgok3btcn.png',
    'Leonard Taylor III': 'elc6oyeqxotnsd0jc1lt.png',
    'Greg Van Roten': 'wneyp60hnnobribf9bji.png',
    'Alijah Vera-Tucker': 't0y1s4s7lcejlls6zz9d.png',
    'Kyle Williams': 'h7hitbjkmpeduy2qvwi5.png',
    'Milton Williams': 'fjokafi7rlehto0fqr2n.png',
    'Jared Wilson': 'crg665zi9ftvbb7wjuco.png',
    'Charles Woods': 'l9n1qm7x0cxxyscehj9o.png',
    'Craig Woodson': 'nszcifrcc8lty6s2gfhm.png',
  },
}

export function getRosterHeadshot(category: '2026-hawks' | '2026-pats', name: string): string | null {
  const asset = HEADSHOTS[category]?.[name]
  if (!asset) return null
  const team = category === '2026-hawks' ? 'seahawks' : 'patriots'
  return `https://static.clubs.nfl.com/image/upload/f_auto,q_auto,w_640,c_limit/${team}/${asset}`
}
